<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: pl/_i18n/default/actions/action_import/action_import
  * Revision: 3325
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_import/action_import",
"rev" => "3325",
"time" => "1239219765",
"lang" => "pl",
);
$lang = array (
  'title' => 'Importuj zawartość',
  'upload_explain' => 'Załaduj plik XML zawierający strony do importu. Ten plik można otrzymać używając opcji Export.',
  'upload_file' => 'Plik XML',
  'upload_prefix' => 'Prefiks nazwy stron',
  'upload_prefix_tip' => 'np. : import/',
  'upload_submit' => 'Załaduj teraz',
  'select_explain' => 'Zaznacz te strony które chcesz importować',
  'select_submit' => 'Importuj teraz',
  'notice_content' => 'Niepoprawna zawartość',
  'notice_lang' => 'Niewspierany język',
  'notice_unknown' => 'Nieznany błąd',
  'notice_exists' => 'Strona obecnie w użyciu',
  'process_explain' => 'Rezultat importu :',
  'process_fail' => 'NIEUDANY',
  'process_success' => 'OK',
)
?>