<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: ar/_i18n/default/actions/action_import/action_import
  * Revision: 3317
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_import/action_import",
"rev" => "3317",
"time" => "1239219765",
"lang" => "ar",
);
$lang = array (
  'title' => 'جلب المحتويات',
  'upload_explain' => 'الرجاء تحميل ملف الXML اللذي يحوي الصفحات التي تود جلبها، يمكنك توليد هذا الملف باستخدام خاصية التوليد',
  'upload_file' => 'ملف XML',
  'upload_prefix' => 'المقطع الأول اللذي ستبدأ به أسماء الصفحات',
  'upload_prefix_tip' => 'مثال : import/',
  'upload_submit' => 'حمل الاّن',
  'select_explain' => 'الرجاء إختيار الصفحات التي تود جلبها',
  'select_submit' => 'إجلب الاّن',
  'notice_content' => 'محتوى غير سليم',
  'notice_lang' => 'لغة غير مدعومة',
  'notice_unknown' => 'خطأ غير معلوم',
  'notice_exists' => 'إسم الصفحة قيد الإستعمال حاليا',
  'process_explain' => 'نتيجة الجلب:',
  'process_fail' => 'نأسف، لم تتم العملية بنجاح!',
  'process_success' => 'تمت العملية بنجاح',
)
?>