<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: ro/_i18n/default/actions/action_import/action_import
  * Revision: 3328
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_import/action_import",
"rev" => "3328",
"time" => "1239219766",
"lang" => "ro",
);
$lang = array (
  'title' => 'Importa continut',
  'upload_explain' => 'Incarca un fisier XML ce contine pagini pentru import. Poti obtine asemenea fisiere folosind functia de Export.',
  'upload_file' => 'Fisier XML',
  'upload_prefix' => 'Prefixe nume pagini',
  'upload_prefix_tip' => 'ex : import/',
  'upload_submit' => 'Incarca acum',
  'select_explain' => 'Selecteaza paginile care ai vrea sa le importi',
  'select_submit' => 'Importa acum',
  'notice_content' => 'Continut invalid',
  'notice_lang' => 'Limba nesuportata',
  'notice_unknown' => 'Eroare necunoscuta',
  'notice_exists' => 'Numele paginii este deja in folosinta',
  'process_explain' => 'Rezultatul importului :',
  'process_fail' => 'NEREUSIT',
  'process_success' => 'OK',
)
?>