<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: it/_i18n/default/actions/action_import/action_import
  * Revision: 3324
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_import/action_import",
"rev" => "3324",
"time" => "1239219765",
"lang" => "it",
);
$lang = array (
  'title' => 'Importa il contenuto',
  'upload_explain' => 'Carica un file XML che contiene le pagine da importare. Puoi ottenere un file simile utilizzando l\'opzione Esporta.',
  'upload_file' => 'File XML',
  'upload_prefix' => 'Prefisso delle pagine',
  'upload_prefix_tip' => 'es : importa/',
  'upload_submit' => 'Carica adesso',
  'select_explain' => 'Seleziona le pagine che vorresti importare',
  'select_submit' => 'Importa adesso',
  'notice_php' => 'Non ti si consente di importare codice che contenga PHP',
  'notice_js' => 'Non ti si consente di importare codice che contenga JavaScript',
  'notice_acl' => 'Non si possiede il permesso di importare contenuti in questo punto',
  'notice_content' => 'Contenuto non valido',
  'notice_lang' => 'Lingua non supportata',
  'notice_unknown' => 'Errore sconosciuto',
  'notice_exists' => 'Nome pagina già in uso',
  'process_explain' => 'Risultato dell\'importazione :',
  'process_fail' => 'FALLITO',
  'process_success' => 'OK',
  'process_skipped' => 'SALTATO',
  'filedetails_t' => 'Dettagli del file di Dump',
  'filedetails_time' => 'Ora relativa all\'Esportazione',
  'filedetails_from' => 'Esportato da',
  'filedetails_version' => 'Versione dell\'Esportazione',
)
?>