<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: de/_i18n/default/actions/action_import/action_import
  * Revision: 3319
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_import/action_import",
"rev" => "3319",
"time" => "1239219765",
"lang" => "de",
);
$lang = array (
  'title' => 'Inhalte importieren',
  'upload_explain' => 'Eine XML Datei hochladen, welche Seiten zum Importieren enthält. Sie können eine solche Datei mittels des Export Features erhalten.',
  'upload_file' => 'XML Datei',
  'upload_prefix' => 'Präfix vor die Seitennamen',
  'upload_prefix_tip' => 'ex : Import/',
  'upload_submit' => 'Upload',
  'select_explain' => 'Wählen Sie die Seiten aus, die Sie importieren möchten',
  'select_submit' => 'Importieren',
  'notice_php' => 'Sie sind nicht berechtigt Inhalte, die PHP Code beinhalten, zu importieren',
  'notice_js' => 'Sie sind nicht berechtigt Inhalte, die JavaScript Code beinhalten, zu importieren',
  'notice_acl' => 'Sie sind nicht berechtigt hier Inhalte zu importieren',
  'notice_content' => 'Ungültiger Inhalt',
  'notice_lang' => 'Nicht unterstützte Sprache',
  'notice_unknown' => 'Unbekannter Fehler',
  'notice_exists' => 'Seitenname wird bereits verwendet',
  'process_explain' => 'Import Ergebnis:',
  'process_fail' => 'FEHLGESCHLAGEN',
  'process_success' => 'OK',
  'process_skipped' => 'ÜBERSRPRUNGEN',
  'filedetails_t' => 'Liste Dateiinformationen auf',
  'filedetails_time' => 'Export-Zeit',
  'filedetails_from' => 'Exportiert von',
  'filedetails_version' => 'Exportierte Version',
)
?>