<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: fr/_i18n/default/actions/action_import/action_import
  * Revision: 3322
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_import/action_import",
"rev" => "3322",
"time" => "1239219765",
"lang" => "fr",
);
$lang = array (
  'title' => 'Importer du contenu',
  'upload_explain' => 'Transférer un fichier XML contenant les pages à importer. Vous pouvez obtenir un tel fichier en utilisant la fonction d\'exportation.',
  'upload_file' => 'Fichier XML',
  'upload_prefix' => 'Ajouter un préfixe aux noms de page',
  'upload_prefix_tip' => 'ex : importer/',
  'upload_submit' => 'Transférer maintenant',
  'select_explain' => 'Choisissez les pages que vous souhaitez importer',
  'select_submit' => 'Importer maintenant',
  'notice_php' => 'Vous n\'avez pas l\'autorisation d\'importer des pages contenant du code PHP',
  'notice_js' => 'Vous n\'avez pas l\'autorisation d\'importer des pages contenant du code JavaScript',
  'notice_acl' => 'Vous n\'avez pas l\'autorisation d\'importer des contenus ici.',
  'notice_content' => 'Contenu invalide',
  'notice_lang' => 'Langue non prise en charge',
  'notice_unknown' => 'Erreur inconnue',
  'notice_exists' => 'Nom de page déjà utilisé',
  'process_explain' => 'Résultat de l\'importation :',
  'process_fail' => 'ÉCHOUÉ',
  'process_success' => 'OK',
  'process_skipped' => 'IGNORÉ',
  'filedetails_t' => 'Détails du fichier d\'exportation',
  'filedetails_time' => 'Heure d\'exportation',
  'filedetails_from' => 'Exporté depuis',
  'filedetails_version' => 'Version d\'exportation',
)
?>