<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_import/action_import
  * Revision: 3332
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_import/action_import",
"rev" => "3332",
"time" => "1239219766",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '导入内容',
  'upload_explain' => '上传一个包含XML文件内容的页面以导入.你可以用 Export功能得到一个这样的文件.',
  'upload_file' => 'XML 文件',
  'upload_prefix' => '前缀页名',
  'upload_prefix_tip' => '举例 : import/',
  'upload_submit' => '现在上传',
  'select_explain' => '选择你想导入的页面',
  'select_submit' => '现在导入',
  'notice_content' => '不正确的内容',
  'notice_lang' => '未被支持的语言',
  'notice_unknown' => '未知错误',
  'notice_exists' => '页面名已被使用',
  'process_explain' => '导入结果 :',
  'process_fail' => '已失败',
  'process_success' => 'OK',
)
?>