<?php
$lang = array (
	"naventry"			=>	"Export contents",
	"naventry_desc"		=>	"Export contents to an XML file",
	"title"					=>	"Export contents",
	"export_submit"				=>	"Export to XML file",
	"notice_php"			=>	"PHP access denied",
	"notice_acl"			=>	"Export ACL denied",
	"explain"			=>	"Select the pages you would like to export as an XML file",
	"xmlcomment_info"	=>	"This is a dump generated by Anwiki",
	"xmlcomment_time"	=>	"Generated on: %time%",
	"xmlcomment_user"	=>	"User: %user%",
	"xmlcomment_version"	=>	"Anwiki version: %version%",
	"xmlcomment_from"	=>	"Exported from: %url%",
	"xmlcomment_contents"=>	"The following contents have been exported:",
);
?>