<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: pl/_i18n/default/actions/action_export/action_export
  * Revision: 3293
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_export/action_export",
"rev" => "3293",
"time" => "1239219767",
"lang" => "pl",
);
$lang = array (
  'naventry' => 'Eksport zawartości',
  'export_submit' => 'Eksport do pliku XML',
  'notice_php' => 'PHP dostęp zabroniony',
  'notice_acl' => 'Eksport ACL zabroniony',
  'explain' => 'Zaznacz strony które chcesz eksportować jako plik XML',
  'xmlcomment_info' => 'To jest zrzut wygenerowany przez Anwiki',
  'xmlcomment_time' => 'Wygenerowano o: %time%',
  'xmlcomment_user' => 'Użytkownik: %user%',
  'xmlcomment_version' => 'Wersja Anwiki: %version%',
  'xmlcomment_from' => 'Wyeksportowano z: %url%',
  'xmlcomment_contents' => 'Następująca zawartość została wyeksportowana:',
)
?>