<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: de/_i18n/default/actions/action_export/action_export
  * Revision: 3287
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_export/action_export",
"rev" => "3287",
"time" => "1239219767",
"lang" => "de",
);
$lang = array (
  'naventry' => 'Inhalte exportieren',
  'export_submit' => 'Als XML Datei exportieren',
  'notice_php' => 'PHP Zugriff verweigert',
  'notice_acl' => 'ACL Export verweigert',
  'explain' => 'Wählen Sie die Seiten aus, die Sie als XML Datei exportieren möchten',
  'xmlcomment_info' => 'Dies ist ein Abbild generiert durch Anwiki',
  'xmlcomment_time' => 'Generiert am: %time%',
  'xmlcomment_user' => 'Benutzer: %user%',
  'xmlcomment_version' => 'Anwiki Version: %version%',
  'xmlcomment_from' => 'Exportiert von: %url%',
  'xmlcomment_contents' => 'Die folgenden Inhalte wurden exportiert:',
)
?>