<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: fr/_i18n/default/actions/action_export/action_export
  * Revision: 3290
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_export/action_export",
"rev" => "3290",
"time" => "1239219767",
"lang" => "fr",
);
$lang = array (
  'naventry' => 'Exporter les contenus',
  'export_submit' => 'Exporter vers un fichier XML',
  'notice_php' => 'Accès PHP refusé',
  'notice_acl' => 'Exportation des ACL refusée',
  'explain' => 'Sélectionnez les pages que vous souhaitez exporter en tant que fichier XML',
  'xmlcomment_info' => 'Ceci est un export généré par Anwiki',
  'xmlcomment_time' => 'Généré le : %time%',
  'xmlcomment_user' => 'Utilisateur : %user%',
  'xmlcomment_version' => 'Version d\'Anwiki : %version%',
  'xmlcomment_from' => 'Exporté de : %url%',
  'xmlcomment_contents' => 'Les contenus suivants ont été exportés :',
)
?>