<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_export/action_export
  * Revision: 3300
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_export/action_export",
"rev" => "3300",
"time" => "1239219767",
"lang" => "zh_CN",
);
$lang = array (
  'export_submit' => '输出到 XML 文件',
  'notice_php' => 'PHP 存取拒绝',
  'notice_acl' => '输出 ACL 拒绝',
  'explain' => '选择你想输出为XML文件的页面',
)
?>