<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: it/_i18n/default/actions/action_export/action_export
  * Revision: 3292
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_export/action_export",
"rev" => "3292",
"time" => "1239219767",
"lang" => "it",
);
$lang = array (
  'naventry' => 'Esporta contenuti',
  'export_submit' => 'Esporta su file XML',
  'notice_php' => 'Accesso PHP negato',
  'notice_acl' => 'Esportazione  ACL negata',
  'explain' => 'Seleziona le pagine che vorresti esportare come file XML',
  'xmlcomment_info' => 'Questo è un dump generato da Anwiki',
  'xmlcomment_time' => 'Generato alle: %time%',
  'xmlcomment_user' => 'Utente: %user%',
  'xmlcomment_version' => 'Versione di Anwiki: %version%',
  'xmlcomment_from' => 'Esportato da: %url%',
  'xmlcomment_contents' => 'Sono stati esportati i seguenti contenuti:',
)
?>