<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: ar/_i18n/default/actions/action_export/action_export
  * Revision: 3285
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_export/action_export",
"rev" => "3285",
"time" => "1239219767",
"lang" => "ar",
);
$lang = array (
  'export_submit' => 'توليد المحتويات على شكل ملف XML',
  'notice_php' => 'ممنوع الدخول "الوارد من PHP"',
  'notice_acl' => 'ممنوع توليد ACL',
  'explain' => 'الرجاء إختيار الصفحات التي تود أن تولد منها ملف الXML',
)
?>