<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_view/action_view
  * Revision: 3604
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_view/action_view",
"rev" => "3604",
"time" => "1239219764",
"lang" => "zh_CN",
);
$lang = array (
  'local_version' => '最后编辑在 %time%',
  'local_notice_incomplete' => '这个页面可能部分被翻译或者它的内容已经过时. 你可以帮助我们翻译它 %lnkopen% 点击这个连接 %lnkclose%',
)
?>