<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: it/_i18n/default/actions/action_view/action_view
  * Revision: 3596
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_view/action_view",
"rev" => "3596",
"time" => "1239219764",
"lang" => "it",
);
$lang = array (
  'local_version' => 'Modificato l\'ultima volta il %time%',
  'local_notice_incomplete' => 'Questa pagina può essere stata tradotta parzialmente o il suo contenuto può essere obsoleto. Puoi aiutarci a tradurla %lnkopen%cliccando su questo collegamento%lnkclose%',
)
?>