<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: fr/_i18n/default/actions/action_view/action_view
  * Revision: 3594
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_view/action_view",
"rev" => "3594",
"time" => "1239219763",
"lang" => "fr",
);
$lang = array (
  'local_version' => 'Dernière modification le %time%',
  'local_notice_incomplete' => 'Cette page n\'a été que partiellement traduite ou a subi des modifications. Vous pouvez nous aider à la traduire %lnkopen%en cliquant sur ce lien%lnkclose%',
)
?>