<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: de/_i18n/default/actions/action_view/action_view
  * Revision: 3591
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_view/action_view",
"rev" => "3591",
"time" => "1239219763",
"lang" => "de",
);
$lang = array (
  'local_version' => 'Zuletzt editiert am %time%',
  'local_notice_incomplete' => 'Diese Seite ist eventuell teilweise übersetzt oder ihr Inhalt könnte veraltet sein. Sie können uns bei der Übersetzung helfen indem Sie %lnkopen%auf diesen Link klicken%lnkclose%',
)
?>