<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: ar/_i18n/default/actions/action_view/action_view
  * Revision: 3589
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_view/action_view",
"rev" => "3589",
"time" => "1239219763",
"lang" => "ar",
);
$lang = array (
  'local_version' => 'اخر تعديل تم في %time%',
  'local_notice_incomplete' => 'ربما تم تعديل هذه الصفحة بشكل جزئي أو أن هذه الصفحة غير محدثة، تستطيع أن تساعدنا في ترجمتها %lnkopen% عن طريق النقر على هذا الرابط %lnkclose%',
)
?>