<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: ro/_i18n/default/actions/action_view/action_view
  * Revision: 3600
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_view/action_view",
"rev" => "3600",
"time" => "1239219764",
"lang" => "ro",
);
$lang = array (
  'local_version' => 'Ultima editare la %time%',
  'local_notice_incomplete' => 'Aceasta pagina este tradusa partial sau continutul sau poate fi invechit. Ne poti ajuta sa o traducem %lnkopen%apasand pe acest link%lnkclose%',
)
?>