<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: pl/_i18n/default/actions/action_view/action_view
  * Revision: 3597
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_view/action_view",
"rev" => "3597",
"time" => "1239219764",
"lang" => "pl",
);
$lang = array (
  'local_version' => 'Ostatnio edytowano o %time%',
  'local_notice_incomplete' => 'Ta strona być może została częściowo przetłumaczona lub jej zawartość może być nieaktualna. Możesz pomóc nam w jej tłumaczeniu %lnkopen%klikając na ten link%lnkclose%',
)
?>