<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: ar/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3573
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3573",
"time" => "1239219767",
"lang" => "ar",
);
$lang = array (
  'naventry' => 'الصفحات الغير مترجمة',
)
?>