<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: ro/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3584
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3584",
"time" => "1239219767",
"lang" => "ro",
);
$lang = array (
  'naventry' => 'Pagini netraduse',
)
?>