<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: pl/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3581
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3581",
"time" => "1239219767",
"lang" => "pl",
);
$lang = array (
  'naventry' => 'Strony nieprzetłumaczone',
)
?>