<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: fr/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3578
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3578",
"time" => "1239219767",
"lang" => "fr",
);
$lang = array (
  'naventry' => 'Pages non traduites',
)
?>