<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: de/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3575
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3575",
"time" => "1239219767",
"lang" => "de",
);
$lang = array (
  'naventry' => 'Unübersetzte Seiten',
)
?>