<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: it/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3580
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3580",
"time" => "1239219767",
"lang" => "it",
);
$lang = array (
  'naventry' => 'Pagine non ancora tradotte',
)
?>