<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_untranslated/action_untranslated
  * Revision: 3588
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_untranslated/action_untranslated",
"rev" => "3588",
"time" => "1239219767",
"lang" => "zh_CN",
);
$lang = array (
  'naventry' => '未翻译页面',
)
?>