<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: pl/_i18n/default/actions/action_management/action_management
  * Revision: 3421
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_management/action_management",
"rev" => "3421",
"time" => "1239219763",
"lang" => "pl",
);
$lang = array (
  'explain' => 'Oto są użyteczne narzędzia by zarządzac zawartością',
)
?>