<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: it/_i18n/default/actions/action_management/action_management
  * Revision: 3420
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_management/action_management",
"rev" => "3420",
"time" => "1239219763",
"lang" => "it",
);
$lang = array (
  'explain' => 'Ecco degli strumenti utili a gestire i vostri contenuti.',
)
?>