<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: fr/_i18n/default/actions/action_management/action_management
  * Revision: 3418
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_management/action_management",
"rev" => "3418",
"time" => "1239219763",
"lang" => "fr",
);
$lang = array (
  'explain' => 'Ici se trouvent des outils utiles pour la gestion de vos contenus',
)
?>