<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: de/_i18n/default/actions/action_management/action_management
  * Revision: 3415
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_management/action_management",
"rev" => "3415",
"time" => "1239219763",
"lang" => "de",
);
$lang = array (
  'explain' => 'Hier sind einige nutzvolle Tools zur Verwaltung Ihrerer Inhalte',
)
?>