<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: ar/_i18n/default/actions/action_management/action_management
  * Revision: 3413
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_management/action_management",
"rev" => "3413",
"time" => "1239219763",
"lang" => "ar",
);
$lang = array (
  'explain' => 'أدوات مفيدة لإدارة محتوياتك',
)
?>