<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_management/action_management
  * Revision: 3428
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_management/action_management",
"rev" => "3428",
"time" => "1239219763",
"lang" => "zh_CN",
);
$lang = array (
  'explain' => '这里是管理你的内容的有用工具',
)
?>