<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: ar/_i18n/default/actions/action_changelang/action_changelang
  * Revision: 3157
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_changelang/action_changelang",
"rev" => "3157",
"time" => "1239219767",
"lang" => "ar",
);
$lang = array (
  'title' => 'تغيير اللغة لصفحة %pagename%',
)
?>