<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:48
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_changelang/action_changelang
  * Revision: 3172
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_changelang/action_changelang",
"rev" => "3172",
"time" => "1239219768",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '改变 %pagename% 的语言',
)
?>