<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: de/_i18n/default/actions/action_changelang/action_changelang
  * Revision: 3159
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_changelang/action_changelang",
"rev" => "3159",
"time" => "1239219767",
"lang" => "de",
);
$lang = array (
  'title' => 'Sprache wechseln für %pagename%',
)
?>