<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:48
  * By: anw
  * From: it/_i18n/default/actions/action_changelang/action_changelang
  * Revision: 3164
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_changelang/action_changelang",
"rev" => "3164",
"time" => "1239219768",
"lang" => "it",
);
$lang = array (
  'title' => 'Cambia la lingua per %pagename%',
)
?>