<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:48
  * By: anw
  * From: pl/_i18n/default/actions/action_changelang/action_changelang
  * Revision: 3165
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_changelang/action_changelang",
"rev" => "3165",
"time" => "1239219768",
"lang" => "pl",
);
$lang = array (
  'title' => 'Zmiana języka dla %pagename%',
)
?>