<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: fr/_i18n/default/actions/action_changelang/action_changelang
  * Revision: 3162
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_changelang/action_changelang",
"rev" => "3162",
"time" => "1239219767",
"lang" => "fr",
);
$lang = array (
  'title' => 'Changer la langue pour %pagename%',
)
?>