<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: fr/_i18n/default/actions/action_rename/action_rename
  * Revision: 3482
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_rename/action_rename",
"rev" => "3482",
"time" => "1239219766",
"lang" => "fr",
);
$lang = array (
  'title' => 'Renommer la page %pagename%',
  'rename_updatelinks' => 'Mettre à jour automatiquement les liens se rapportant à cette page',
  'rename_links' => 'Les pages suivantes ont des liens se rapportant à cette page :',
)
?>