<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: pl/_i18n/default/actions/action_rename/action_rename
  * Revision: 3485
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_rename/action_rename",
"rev" => "3485",
"time" => "1239219766",
"lang" => "pl",
);
$lang = array (
  'title' => 'Zmień nazwę strony %pagename%',
  'rename_updatelinks' => 'Automatyczne uaktualnienie linków odnoszących się do tej strony',
  'rename_links' => 'Nasŧepujące strony posiadają odnośniki do tej strony :',
)
?>