<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: ar/_i18n/default/actions/action_rename/action_rename
  * Revision: 3477
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_rename/action_rename",
"rev" => "3477",
"time" => "1239219766",
"lang" => "ar",
);
$lang = array (
  'title' => 'تغيير إسم الصفحة %pagename%',
  'rename_updatelinks' => 'التعديل التلقائي للروابط اللتي تتعامل مع هذه الصفحة',
  'rename_links' => 'تحتوي الصفحات التالية على روابط تؤشر على هذه الصفحة:',
)
?>