<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_rename/action_rename
  * Revision: 3492
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_rename/action_rename",
"rev" => "3492",
"time" => "1239219766",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '重命名页面 %pagename%',
  'rename_updatelinks' => '自动更新与这个页面相关的连接',
  'rename_links' => '以下页面有与这个页面相关的连接:',
)
?>