<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: de/_i18n/default/actions/action_rename/action_rename
  * Revision: 3479
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_rename/action_rename",
"rev" => "3479",
"time" => "1239219766",
"lang" => "de",
);
$lang = array (
  'title' => 'Umbenennen der Seite %pagename%',
  'rename_updatelinks' => 'Automatisch Links, die auf diese Seite verweisen aktualisieren',
  'rename_links' => 'Folgende Seiten verweisen auf diese Seite:',
)
?>