<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: it/_i18n/default/actions/action_rename/action_rename
  * Revision: 3484
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_rename/action_rename",
"rev" => "3484",
"time" => "1239219766",
"lang" => "it",
);
$lang = array (
  'title' => 'Rinomina la pagina %pagename%',
  'rename_updatelinks' => 'Aggiorna automaticamente i collegamenti verso questa pagina',
  'rename_links' => 'Le pagine seguenti contengono collegamenti verso questa pagina :',
)
?>