<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:49
  * By: anw
  * From: gr/_i18n/default/global/global/global
  * Revision: 4354
  */
$anwiki_build = array(
"from" => "gr/_i18n/default/global/global/global",
"rev" => "4354",
"time" => "1239220249",
"lang" => "gr",
);
$lang = array (
  'local_html_lang' => 'gr',
  'local_html_dir' => 'ltr',
  'local_title_before' => '',
  'local_title_after' => '',
  'footer' => '',
)
?>