<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: pt/_i18n/default/global/global/global
  * Revision: 4358
  */
$anwiki_build = array(
"from" => "pt/_i18n/default/global/global/global",
"rev" => "4358",
"time" => "1239220250",
"lang" => "pt",
);
$lang = array (
  'in_pagename' => 'Nome da página :',
  'in_pagelang' => 'Idioma da Página :',
  'in_contentclass' => 'Class da Página :',
  'in_comment' => 'Comentário :',
  'in_submit' => 'Ok',
  'in_abort' => 'Abortar',
  'in_chkall' => 'tudo',
  'in_chknone' => 'nenhum',
  'in_filter' => 'Filtro',
  'topnav_settings' => 'opções',
  'topnav_login' => 'entrar',
  'topnav_logout' => 'sair',
  'topnav_register' => 'registar',
  'err_404' => '404 - O URL não foi encontrado.',
  'err_occurred' => 'Ocorreu um erro',
  'err_badpagename' => 'Nome de página ilegal: nenhuma página pode ter tal nome',
  'err_badlang' => 'Idioma ilegal : o código do idioma é inválido',
  'err_badtimezone' => 'Fuso horário ilegal : Este fuso horário não é válido',
  'err_auth' => 'Não há nenhum registo com esse username e password',
  'err_emptyfields' => 'É obrigatório preencher todos os campos obrigatórios',
  'err_pwdlength' => 'O Comprimento da password deve ser pelo menos de %minlength% caracteres',
  'err_unkn' => 'Um erro desconhecido ocorreu, tente novamente mais tarde',
  'err_badcall' => 'Link Quebrado, o link que clicou parece não estar a funcionar',
  'err_pagealreadyexists' => 'Já existe uma página com esse nome',
  'err_badlogin' => 'Login Inválido',
  'err_baddisplayname' => 'Nome Inválido',
  'err_bademail' => 'E-mail Inválido',
  'err_unknownlogin' => 'Login desconhecido',
  'err_badpassword' => 'Password inválida',
  'err_passwordsmatch' => 'A password repetida não é igual',
  'err_badcaptcha' => 'Código anti-spam errado',
  'err_nopermission' => 'Não está autorizado a efectuar esta acção',
  'err_langexistsforpagegroup' => 'Já existe uma tradução com este nome',
  'err_ex_report' => 'Erro foi registado. Por favor tente dentro de alguns minutos, ou contacte o administrador enviando o seguinte número de erro : %errornumber%',
  'err_ex_sorry' => 'Pedimos desculpa pelo transtorno',
  'err_ex_unexpected_t' => 'Erro inesperado ocorreu',
  'err_ex_unexpected_p' => 'O sistema não conseguiu completar o pedido devido a um erro interno. Isto pode talvez ser um bug.',
  'err_ex_acl_t' => 'Permissão Negada',
  'local_datetime' => 'm/d/Y H:i:s',
  'local_date' => 'm/d/Y',
  'local_html_lang' => 'pt',
  'local_html_dir' => 'ltr',
  'local_title_before' => '',
  'local_title_after' => '',
  'footer' => '',
)
?>