<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: ro/_i18n/default/global/global/global-editcontent
  * Revision: 3840
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/global/global/global-editcontent",
"rev" => "3840",
"time" => "1239220250",
"lang" => "ro",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'XML eronat : %xmlerrors%',
  'err_contentfield_date_format' => 'Format data invalida. Format valid : %dateformat%',
  'err_contentfield_number_min' => 'Valuare minima : %minval%',
  'err_contentfield_number_max' => 'Valuare maxima : %maxval%',
  'err_contentfield_acl_php' => 'Nu ai permisiunile sa poti edita continutul avand cod PHP.',
  'err_contentmultiplicity_single_notfound' => 'Nici o valuare gasita',
  'err_contentmultiplicity_single_unexpected' => 'Mai mult de o valuare gasita (bug?)',
  'err_contentmultiplicity_multiple_min' => 'Numar minim de  %elementname% : %minval%',
  'contentfield_link_single' => 'link',
  'contentfield_link_title_label' => 'Titlu link',
  'contentfield_link_url_label' => 'URL link',
  'contentfield_link_target_label' => 'Tinta',
  'contentfield_link_target_self' => 'Aceeasi fereastra',
  'contentfield_link_target_blank' => 'Fereastra noua',
  'datatype_xml_tip' => 'Orice XML valid este permid',
  'datatype_date_tip' => 'Format : %dateformat%',
  'datatype_string_tip' => 'Orice text exceptand urmatoarele caractere : %forbiddenchars%',
  'datatype_enum_tip' => 'Una din variabilele selectabile',
  'contentmultiplicity_multiple_tip_between' => 'Intre %mincount% si %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_greater' => 'Cel putin %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => 'Cel mult %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => 'Orice numar de %contentfield%',
  'contentmultiplicity_multiple_tip_fixed' => 'Exact %count% %contentfield%',
)
?>