<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: it/_i18n/default/global/global/global-editcontent
  * Revision: 3836
  */
$anwiki_build = array(
"from" => "it/_i18n/default/global/global/global-editcontent",
"rev" => "3836",
"time" => "1239220250",
"lang" => "it",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'XML malformato : %xmlerrors%',
  'err_contentfield_date_format' => 'Data errata. Formato atteso : %dateformat%',
  'err_contentfield_integer_numeric' => 'E\' atteso un numero intero',
  'err_contentfield_number_min' => 'Valore minimo : %minval%',
  'err_contentfield_number_max' => 'Valore massimo : %maxval%',
  'err_contentfield_enum_values' => 'Ci si aspettava uno dei seguenti valori : %enumvalues%',
  'err_contentfield_acl_php' => 'Non hai i permessi per poter modificare contenuti in codice PHP.',
  'err_contentmultiplicity_single_notfound' => 'Non è stato trovato alcun valore',
  'err_contentmultiplicity_single_unexpected' => 'E\' stato trovato più di un valore (errore?)',
  'err_contentmultiplicity_multiple_min' => 'Numero minimo di %elementname% : %minval%',
  'contentfield_link_single' => 'collegamento',
  'contentfield_link_title_label' => 'Titolo del collegamento',
  'contentfield_link_url_label' => 'URL del collegamento',
  'contentfield_link_target_label' => 'Obiettivo',
  'contentfield_link_target_self' => 'Stessa finestra',
  'contentfield_link_target_blank' => 'Nuova finestra',
  'datatype_xml_tip' => 'Qualsiasi XML valido è ammesso',
  'datatype_date_tip' => 'Formato : %dateformat%',
  'datatype_string_tip' => 'Qualsiasi testo eccetto questi caratteri : %forbiddenchars%',
  'datatype_boolean_legend' => 'Si',
  'datatype_number_tip_between' => 'Qualsiasi %numbertype% compreso tra %minval% e %maxval%',
  'datatype_number_tip_greater' => 'Qualsiasi %numbertype% maggiore di %minval%',
  'datatype_number_tip_lower' => 'Qualsiasi %numbertype% minore di %maxval%',
  'datatype_number_tip_any' => 'Qualsiasi %numbertype%',
  'datatype_number_integer' => 'intero',
  'datatype_number_float' => 'decimale',
  'datatype_enum_tip' => 'Uno dei valori selezionabili',
  'contentmultiplicity_multiple_tip_between' => 'Tra %mincount% e %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_greater' => 'Almeno %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => 'Non più di %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => 'Qualsiasi numero di %contentfield%',
  'contentmultiplicity_multiple_tip_fixed' => 'Esattamente %count% %contentfield%',
)
?>