<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: fr/_i18n/default/global/global/global-editcontent
  * Revision: 3834
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/global/global/global-editcontent",
"rev" => "3834",
"time" => "1239220250",
"lang" => "fr",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'Code XML malformé : %xmlerrors%',
  'err_contentfield_date_format' => 'Date incorrecte. Format attendu : %dateformat%',
  'err_contentfield_integer_numeric' => 'Un nombre entier est attendu',
  'err_contentfield_number_min' => 'Valeur minimale : %minval%',
  'err_contentfield_number_max' => 'Valeur maximale : %maxval%',
  'err_contentfield_enum_values' => 'Une des valeurs sélectionnables est attendue',
  'err_contentfield_acl_php' => 'Vous n\'avez pas la permission de modifier un contenu avec du code PHP.',
  'err_contentmultiplicity_single_notfound' => 'Aucune valeur trouvée',
  'err_contentmultiplicity_single_unexpected' => 'Plus d\'une valeur a été trouvée (bug ?)',
  'err_contentmultiplicity_multiple_min' => 'Nombre maximum de %elementname% : %minval%',
  'contentfield_link_single' => 'lien',
  'contentfield_link_title_label' => 'Titre du lien',
  'contentfield_link_url_label' => 'URL du lien',
  'contentfield_link_target_label' => 'Cible',
  'contentfield_link_target_self' => 'Même fenêtre',
  'contentfield_link_target_blank' => 'Nouvelle fenêtre',
  'datatype_xml_tip' => 'Tout code XML bien formé',
  'datatype_date_tip' => 'Format : %dateformat%',
  'datatype_string_tip' => 'Tout texte, excepté les caractères : %forbiddenchars%',
  'datatype_boolean_legend' => 'Oui',
  'datatype_number_tip_between' => 'Tout %numbertype% compris entre %minval% et %maxval%',
  'datatype_number_tip_greater' => 'Tout %numbertype% supérieur à %minval%',
  'datatype_number_tip_lower' => 'Tout %numbertype% inférieur à %maxval%',
  'datatype_number_tip_any' => 'N\'importe quel %numbertype%',
  'datatype_number_integer' => 'nombre entier',
  'datatype_number_float' => 'nombre flottant',
  'datatype_enum_tip' => 'L\'une des valeurs sélectionnables',
  'contentmultiplicity_multiple_tip_between' => 'Entre %mincount% et %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_greater' => 'Au moins %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => 'Au plus %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => 'Autant de %contentfield% que vous le souhaitez',
  'contentmultiplicity_multiple_tip_fixed' => 'Exactement %count% %contentfield%',
)
?>