<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:52
  * By: anw
  * From: zh_CN/_i18n/default/global/global/global-settings
  * Revision: 3860
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/global/global/global-settings",
"rev" => "3860",
"time" => "1239220252",
"lang" => "zh_CN",
);
$lang = array (
  'setting_setup_location_explain' => '',
  'setting_setup_i18n_explain' => '',
  'setting_components_drivers_explain' => '',
  'setting_components_modules_plugins_explain' => '',
  'setting_components_modules_contentclasses_explain' => '',
  'setting_components_modules_actions_explain' => '',
  'setting_advanced_statics_shared_explain' => '',
  'setting_advanced_statics_shared_enabled_explain' => '',
  'setting_advanced_statics_shared_url_explain' => '',
  'setting_advanced_statics_setup_explain' => '',
  'setting_advanced_statics_setup_enabled_explain' => '',
  'setting_advanced_statics_setup_url_explain' => '',
)
?>