<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:49
  * By: anw
  * From: lt/_i18n/default/global/global/global
  * Revision: 4356
  */
$anwiki_build = array(
"from" => "lt/_i18n/default/global/global/global",
"rev" => "4356",
"time" => "1239220249",
"lang" => "lt",
);
$lang = array (
  'local_title_before' => '',
  'local_title_after' => '',
  'footer' => '',
)
?>