<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: sl/_i18n/default/global/global/global
  * Revision: 4362
  */
$anwiki_build = array(
"from" => "sl/_i18n/default/global/global/global",
"rev" => "4362",
"time" => "1239220250",
"lang" => "sl",
);
$lang = array (
  'in_pagename' => 'Ime strani:',
  'in_pagelang' => 'Jezik strani:',
  'in_contentclass' => 'Razred strani:',
  'in_comment' => 'Komantar:',
  'in_submit' => 'V redu',
  'in_abort' => 'Zapusti',
  'in_chkall' => 'vse',
  'in_chknone' => 'nič',
  'in_filter' => 'Filter',
  'topnav_settings' => 'nastavitve',
  'topnav_login' => 'prijava',
  'topnav_logout' => 'odjava',
  'topnav_register' => 'registracija',
  'err_occurred' => 'Zaznana je bila napaka',
  'local_html_lang' => 'sl',
  'local_html_dir' => 'ltr',
  'local_title_before' => '',
  'local_title_after' => '',
  'footer' => '',
)
?>