<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: pt_BR/_i18n/default/global/global/global
  * Revision: 4359
  */
$anwiki_build = array(
"from" => "pt_BR/_i18n/default/global/global/global",
"rev" => "4359",
"time" => "1239220250",
"lang" => "pt_BR",
);
$lang = array (
  'local_datetime' => 'm/d/Y H:i:s',
  'local_date' => 'm/d/Y',
  'local_html_lang' => 'pt_BR',
  'local_html_dir' => 'ltr',
  'local_title_before' => '',
  'local_title_after' => '',
  'footer' => '',
)
?>