<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: ar/_i18n/default/global/global/global-editcontent
  * Revision: 3829
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/global/global/global-editcontent",
"rev" => "3829",
"time" => "1239220250",
"lang" => "ar",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'محتوى XML غير سليم: %xmlerrors%',
  'err_contentfield_date_format' => 'تاريخ غير سليم، صيغة التاريخ المتوقعة هي: %dateformat%',
  'err_contentfield_integer_numeric' => 'يتوقع منك إدخال رقم',
  'err_contentfield_number_min' => 'الحد الأدنى يتمثل ب: %minval%',
  'err_contentfield_number_max' => 'الحد الأعلى يتمثل ب: %maxval%',
  'err_contentfield_acl_php' => 'لا يوجد لك صلاحيات للقيام بتعديل أو إضافة المحتويات التي تحتوي على شيفرة مصدرية مكتوية بلغة PHP',
  'err_contentmultiplicity_single_notfound' => 'لم يتم إيجاد قيمة',
  'err_contentmultiplicity_single_unexpected' => 'تم إيجاد أكثر من قيمة (هل تعتبر ذلك خطأً؟)',
  'err_contentmultiplicity_multiple_min' => 'الحد الأدنى من %elementname% : %minval%',
  'contentfield_link_single' => 'الرابط',
  'contentfield_link_title_label' => 'عنوان الرابط',
  'contentfield_link_url_label' => 'موقع الرابط',
  'contentfield_link_target_label' => 'الهدف',
  'contentfield_link_target_self' => 'نفس النافذة',
  'contentfield_link_target_blank' => 'نافذة جديدة',
  'datatype_xml_tip' => 'أي محتوى XML سليم فهو مسموح',
  'datatype_date_tip' => 'الصيغة: %dateformat%',
  'datatype_string_tip' => 'أي نص فهو مقبول ما عدا النصوص اللتي تحتوي على الرموز التالية: %forbiddenchars%',
  'datatype_number_tip_between' => 'أي %numbertype% بين %minval% و %maxval%',
  'datatype_number_tip_greater' => 'أي %numbertype% أكبر من %minval%',
  'datatype_number_tip_lower' => 'أي %numbertype% أصغر من %maxval%',
  'datatype_number_tip_any' => 'أي %numbertype%',
  'datatype_number_integer' => 'عدد صحيح',
  'datatype_number_float' => 'عدد كسري',
  'datatype_enum_tip' => 'إحدى القيم القابلة للإختيار',
  'contentmultiplicity_multiple_tip_between' => 'بين %mincount% و %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_greater' => 'على الأقل %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => 'على الأكثر %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => 'أي عدد من %contentfield%',
  'contentmultiplicity_multiple_tip_fixed' => 'بالضبط %count% %contentfield%',
)
?>