<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: de/_i18n/default/global/global/global-editcontent
  * Revision: 3831
  */
$anwiki_build = array(
"from" => "de/_i18n/default/global/global/global-editcontent",
"rev" => "3831",
"time" => "1239220250",
"lang" => "de",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'Fehlerhafte XML : %xmlerrors%',
  'err_contentfield_date_format' => 'Unerlaubtes Datum. Erwartetes Format: %dateformat%',
  'err_contentfield_integer_numeric' => 'Eine Ganzzahl wird erwartet',
  'err_contentfield_number_min' => 'Minimaler Wert: %minval%',
  'err_contentfield_number_max' => 'Maximaler Wert: %maxval%',
  'err_contentfield_enum_values' => 'Einer der folgenden auswählbaren Werte wird erwartet: %enumvalues%',
  'err_contentfield_acl_php' => 'Ihnen fehlt die Berechtigung Inhalte zu editieren, die PHP Code beinhalten.',
  'err_contentmultiplicity_single_notfound' => 'Kein Wert gefunden',
  'err_contentmultiplicity_single_unexpected' => 'Mehr als ein Wert gefunden (bug?)',
  'err_contentmultiplicity_multiple_min' => 'Minimale Anzahl an %elementname%: %minval%',
  'contentfield_link_single' => 'Link',
  'contentfield_link_title_label' => 'Link Name',
  'contentfield_link_url_label' => 'Link URL',
  'contentfield_link_target_label' => 'Ziel',
  'contentfield_link_target_self' => 'Gleiches Fenster',
  'contentfield_link_target_blank' => 'Neues Fenster',
  'datatype_xml_tip' => 'Jede gültige XML ist erlaubt',
  'datatype_date_tip' => 'Format: %dateformat%',
  'datatype_string_tip' => 'Jeder Text ohne folgende Zeichen: %forbiddenchars%',
  'datatype_boolean_legend' => 'Ja',
  'datatype_number_tip_between' => 'Alle %numbertype% zwischen %minval% und %maxval%',
  'datatype_number_tip_greater' => 'Alle %numbertype% größer als %minval%',
  'datatype_number_tip_lower' => 'Alle %numbertype% kleiner als %maxval%',
  'datatype_number_tip_any' => 'Alle %numbertype%',
  'datatype_number_integer' => 'Ganzzahl',
  'datatype_number_float' => 'Kommazahl',
  'datatype_enum_tip' => 'Einer der auswählbaren Werte',
  'contentmultiplicity_multiple_tip_between' => 'Zwischen %mincount% und %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_greater' => 'Mindestens %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => 'Höchstens %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => 'Jede Zahl aus %contentfield%',
  'contentmultiplicity_multiple_tip_fixed' => 'Genau %count% %contentfield%',
)
?>