<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:51
  * By: anw
  * From: zh_CN/_i18n/default/global/global/global-editcontent
  * Revision: 3844
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/global/global/global-editcontent",
"rev" => "3844",
"time" => "1239220251",
"lang" => "zh_CN",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'Malformed XML : %xmlerrors%',
  'err_contentfield_date_format' => '不正确的日期，你应该写的格式是： %dateformat%',
  'err_contentfield_integer_numeric' => '需要一个数字',
  'err_contentfield_number_min' => '最小值： %minval%',
  'err_contentfield_number_max' => '最大值： %maxval%',
  'err_contentfield_enum_values' => '以下值之一需要填写: %enumvalues%',
  'err_contentmultiplicity_single_notfound' => '未发现任何值',
  'err_contentmultiplicity_single_unexpected' => '发现一个以上的值(bug?)',
  'err_contentmultiplicity_multiple_min' => '最小值 %elementname% : %minval%',
  'contentfield_link_single' => '连接',
  'contentfield_link_title_label' => '连接标题',
  'contentfield_link_url_label' => '连接地址',
  'contentfield_link_target_label' => '目标',
  'contentfield_link_target_self' => '同一个窗口',
  'contentfield_link_target_blank' => '新窗口',
  'datatype_xml_tip' => '任何正确的XML是允许的',
  'datatype_date_tip' => '格式 : %dateformat%',
  'datatype_string_tip' => '除下列字母外的任何内容 : %forbiddenchars%',
  'datatype_number_tip_between' => '任何在 %minval% 和 %maxval% 之间的整数',
  'datatype_number_tip_greater' => '任何大于 %minval% 的整数',
  'datatype_number_tip_lower' => '任何低于 %maxval% 的整数',
  'datatype_number_tip_any' => '任何整数',
  'datatype_number_integer' => '整数',
  'datatype_number_float' => '浮点数',
  'datatype_enum_tip' => '可以选择的数值之一',
  'contentmultiplicity_multiple_tip_between' => '在 %mincount% 与 %maxcount% %contentfield% 之间',
  'contentmultiplicity_multiple_tip_greater' => '至少 %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => '在大部分的 %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => '任何数量的 %contentfield%',
  'contentmultiplicity_multiple_tip_fixed' => '准确的 %count% %contentfield%',
)
?>