<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: pl/_i18n/default/global/global/global-editcontent
  * Revision: 3837
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/global/global/global-editcontent",
"rev" => "3837",
"time" => "1239220250",
"lang" => "pl",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'Zdeformowany XML : %xmlerrors%',
  'err_contentfield_date_format' => 'Błędna data. Spodziewany format :',
  'err_contentfield_integer_numeric' => 'Spodziewana jest wartość liczbowa',
  'err_contentfield_number_min' => 'Minimalna wartość : %minval%',
  'err_contentfield_number_max' => 'Maksymalna wartość : %maxval%',
  'err_contentfield_enum_values' => 'Jedna z wartości jest wymagana : %enumvalues%',
  'err_contentfield_acl_php' => 'Nie masz wystarczających uprawnień by edytować zawartość zawierającą kod PHP',
  'err_contentmultiplicity_single_notfound' => 'Brak wartości',
  'err_contentmultiplicity_single_unexpected' => 'Znaleziono więcej niż jedną wartość (błąd?)',
  'err_contentmultiplicity_multiple_min' => 'Minimalna liczba %elementname% : %minval%',
  'contentfield_link_single' => 'link',
  'contentfield_link_title_label' => 'Tytuł linku',
  'contentfield_link_url_label' => 'Link URL',
  'contentfield_link_target_label' => 'Cel',
  'contentfield_link_target_self' => 'Obecne okno',
  'contentfield_link_target_blank' => 'Nowe okno',
  'datatype_xml_tip' => 'Każdy poprawny XML jest dozwolony',
  'datatype_date_tip' => 'Format : %dateformat%',
  'datatype_string_tip' => 'Każdy tekst za wyjątkiem następujących znaków : %forbiddenchars%',
  'datatype_boolean_legend' => 'Tak',
  'datatype_number_tip_between' => 'Każda liczba całkowita pomiędzy %minval% i %maxval%',
  'datatype_number_tip_greater' => 'Każda liczba całkowita większa niż %minval%',
  'datatype_number_tip_lower' => 'Każda liczba całkowita mniejsza niż %maxval%',
  'datatype_number_tip_any' => 'Każda liczba całkowita',
  'datatype_number_integer' => 'integer',
  'datatype_number_float' => 'float',
  'datatype_enum_tip' => 'Jedna z wartości do wyboru',
  'contentmultiplicity_multiple_tip_between' => 'Pomiędzy %mincount% i %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_greater' => 'Przynajmniej %mincount% %contentfield%',
  'contentmultiplicity_multiple_tip_lower' => 'W większości %maxcount% %contentfield%',
  'contentmultiplicity_multiple_tip_any' => 'Każde wyliczenie z %contentfield%',
  'contentmultiplicity_multiple_tip_fixed' => 'Dokładnie %count% %contentfield%',
)
?>