<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:52
  * By: anw
  * From: pl/_i18n/default/global/global/global-settings
  * Revision: 3869
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/global/global/global-settings",
"rev" => "3869",
"time" => "1239220252",
"lang" => "pl",
);
$lang = array (
  'setting_setup_label' => 'Setup',
  'setting_setup_explain' => 'Ustawienia odpowiadające setupowi Anwiki.',
  'setting_setup_location_label' => 'Lokacja',
  'setting_setup_location_explain' => '',
  'setting_setup_location_urlroot_label' => 'Główny URL',
  'setting_setup_location_urlroot_explain' => 'URL gdzie Anwiki będzie zainstalowane',
  'setting_setup_location_homepage_label' => 'Home (nazwa zawartości)',
  'setting_setup_location_homepage_explain' => 'Strona, której zawartość będzie domyślnie pokazywana w przypadku dostępu do głównego URL.',
  'setting_setup_location_friendlyurl_enabled_label' => 'Przyjazny URL',
  'setting_setup_location_friendlyurl_enabled_explain' => 'Przyjazny URL jest łatwiejszy w obsłudze dla ludzi i daje lepsze wyniki w rankingach wyszukiwarek sieciowych.<br/>Przed odblokowaniem tej opcji, upewnij się że masz uaktywnioną opcję mod_rewrite w swoim serwerze sieciowym oraz czy plik .htaccess jest obecny w katalogu Anwiki.',
  'setting_setup_location_friendlyurl_enabled_checkbox' => 'Uaktywnij przyjazny URL',
  'setting_setup_location_website_name_label' => 'Nazwa strony sieciowej',
  'setting_setup_location_website_name_explain' => 'Ta nazwa identyfikuje Twoją stronę sieciową. Pojawia się na różnych publicznych lokalizacjach takich jak kanały RSS, e-maile...',
  'setting_setup_i18n_explain' => '',
  'setting_setup_i18n_lang_default_label' => 'Język domyślny',
  'setting_setup_i18n_lang_default_explain' => 'Język domyślny dla setupu Anwiki.',
  'setting_setup_i18n_langs_label' => 'Języki dla treści, w zależności od preferencji',
  'setting_setup_i18n_langs_explain' => 'Masz możliwość tłumaczenia treści w tych językach.<br/>Uwaga, nie usuwaj języka jeśli już posiadasz jakieś treści w tym języku.',
  'setting_setup_i18n_langs_single' => 'język',
  'setting_setup_i18n_langs_plural' => 'języki',
  'setting_setup_i18n_timezone_default_label' => 'Domyślna strefa czasowa',
  'setting_setup_i18n_timezone_default_explain' => 'Domyślna strefa czasowa dla nowych użytkowników.',
  'setting_setup_cookies_label' => 'Ciasteczka',
  'setting_setup_cookies_path_label' => 'ścieżka ciaseczek',
  'setting_setup_cookies_domain_label' => 'domena ciasteczek',
  'setting_setup_prefixes_label' => 'Wielorakie setupy',
  'setting_setup_prefixes_explain' => 'Jeśli uruchomiliście wiele instancji Anwiki na tym samym komputerze-gospodarzu, ustawcie różne prefiksy dla każdej instancji by uniknąć konfliktów.',
  'setting_setup_prefixes_session_label' => 'Prefks sesji',
  'setting_setup_prefixes_cookies_label' => 'Prefiks ciasteczka',
  'setting_components_label' => 'Komponenty',
  'setting_components_explain' => 'Wybierz swoje ulubione komponenty dla setupu Anwiki.',
  'setting_components_drivers_label' => 'Sterowniki',
  'setting_components_drivers_explain' => '',
  'setting_components_drivers_storage_label' => 'Sterownik bazy danych',
  'setting_components_modules_plugins_explain' => '',
  'setting_components_modules_contentclasses_explain' => '',
  'setting_components_modules_actions_explain' => '',
  'setting_advanced_statics_shared_explain' => '',
  'setting_advanced_statics_shared_enabled_explain' => '',
  'setting_advanced_statics_shared_url_explain' => '',
  'setting_advanced_statics_setup_explain' => '',
  'setting_advanced_statics_setup_enabled_explain' => '',
  'setting_advanced_statics_setup_url_explain' => '',
)
?>