<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:50:50
  * By: anw
  * From: pt/_i18n/default/global/global/global-editcontent
  * Revision: 3838
  */
$anwiki_build = array(
"from" => "pt/_i18n/default/global/global/global-editcontent",
"rev" => "3838",
"time" => "1239220250",
"lang" => "pt",
);
$lang = array (
  'err_contentfield_xml_invalid' => 'XML Mal Formado : %xmlerrors%',
  'err_contentfield_date_format' => 'Data Inválida. Formato esperado : %dateformat%',
  'err_contentfield_integer_numeric' => 'Um inteiro é esperado',
  'err_contentfield_number_min' => 'Valor mínimo : %minval%',
  'err_contentfield_number_max' => 'Valor máximo : %maxval%',
  'err_contentmultiplicity_single_notfound' => 'Nenhum valor encontrado',
  'err_contentmultiplicity_single_unexpected' => 'Mais do que um valor encontrado (bug?)',
  'err_contentmultiplicity_multiple_min' => 'Máximo nome de %elementname% : %minval%',
)
?>