<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields
  * Revision: 3621
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields",
"rev" => "3621",
"time" => "1239219818",
"lang" => "ar",
);
$lang = array (
  'contentfield_feed_title_label' => 'عنوان المغذي',
  'contentfield_feed_description_label' => 'وصف المغذي',
)
?>