<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:37
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_feed/contentclass_feed
  * Revision: 3607
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_feed/contentclass_feed",
"rev" => "3607",
"time" => "1239219817",
"lang" => "de",
);
$lang = array (
  'contentclass_feed_label' => 'RSS Feed',
  'local_title' => 'Feed :',
  'local_go_rss' => 'Als RSS exportieren',
)
?>