<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields
  * Revision: 3629
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields",
"rev" => "3629",
"time" => "1239219818",
"lang" => "pl",
);
$lang = array (
  'contentfield_feed_title_label' => 'Tytuł nagłówka',
  'contentfield_feed_description_label' => 'Opis nagłówka',
)
?>