<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_feed/contentclass_feed
  * Revision: 3620
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_feed/contentclass_feed",
"rev" => "3620",
"time" => "1239219818",
"lang" => "zh_CN",
);
$lang = array (
  'contentclass_feed_label' => 'Syndication feed',
  'local_title' => 'Feed :',
  'local_go_rss' => '导出到 RSS',
)
?>