<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields
  * Revision: 3628
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields",
"rev" => "3628",
"time" => "1239219818",
"lang" => "it",
);
$lang = array (
  'contentfield_feed_title_label' => 'Titolo del Feed',
  'contentfield_feed_description_label' => 'Descrizione del Feed',
)
?>