<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields
  * Revision: 3623
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields",
"rev" => "3623",
"time" => "1239219818",
"lang" => "de",
);
$lang = array (
  'contentfield_feed_title_label' => 'Feed Titel',
  'contentfield_feed_description_label' => 'Feed Beschreibung',
)
?>