<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_feed/contentclass_feed
  * Revision: 3612
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_feed/contentclass_feed",
"rev" => "3612",
"time" => "1239219818",
"lang" => "it",
);
$lang = array (
  'contentclass_feed_label' => 'Contenuto del Feed',
  'local_title' => 'Feed :',
  'local_go_rss' => 'Esporta in RSS',
)
?>