<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields
  * Revision: 3636
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields",
"rev" => "3636",
"time" => "1239219818",
"lang" => "zh_CN",
);
$lang = array (
  'contentfield_feed_title_label' => 'Feed 标题',
  'contentfield_feed_description_label' => 'Feed 描述',
)
?>