<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields
  * Revision: 3626
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_feed/contentclass_feed-contentfields",
"rev" => "3626",
"time" => "1239219818",
"lang" => "fr",
);
$lang = array (
  'contentfield_feed_title_label' => 'Titre de l\'article',
  'contentfield_feed_description_label' => 'Description de l\'article',
)
?>