<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:37
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_feed/contentclass_feed
  * Revision: 3610
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_feed/contentclass_feed",
"rev" => "3610",
"time" => "1239219817",
"lang" => "fr",
);
$lang = array (
  'contentclass_feed_label' => 'Syndication d\'articles',
  'local_title' => 'Article :',
  'local_go_rss' => 'Exporter en RSS',
)
?>