<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:37
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_feed/contentclass_feed
  * Revision: 3605
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_feed/contentclass_feed",
"rev" => "3605",
"time" => "1239219817",
"lang" => "ar",
);
$lang = array (
  'contentclass_feed_label' => 'المغذي الإلكتروني',
  'local_title' => 'المغذي',
  'local_go_rss' => 'توليد مغذي إلكتروني من نوع RSS',
)
?>