<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_feed/contentclass_feed
  * Revision: 3613
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_feed/contentclass_feed",
"rev" => "3613",
"time" => "1239219818",
"lang" => "pl",
);
$lang = array (
  'contentclass_feed_label' => 'Nagłowek agencji',
  'local_title' => 'Nagłówek :',
  'local_go_rss' => 'Eksportuj do RSS',
)
?>