<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_translate/action_translate
  * Revision: 4459
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_translate/action_translate",
"rev" => "4459",
"time" => "1239219767",
"lang" => "zh_CN",
);
$lang = array (
  'translate_explain' => '翻译模式 :',
  'translate_explain_1' => '选择一个翻译相关项 : %selectref%',
  'translate_explain_2' => '点击一句话然后输入你的翻译 !',
  'translate_explain_3' => '点击另外一个语句然后用同样的方法翻译它',
  'translate_explain_4' => '当你完成的时候，保存你的杰作 !',
  'translate_button_revert' => '返回',
  'translate_button_save' => '保存全部修改',
  'translate_button_closepanel' => '关闭这个面板',
  'translate_chk_translated' => '标记为已翻译',
  'translate_chk_apply' => '在其他语言中标记为未翻译',
  'translate_button_doneall' => '标记全部内容为已翻译',
  'translate_button_undoneall' => '标记全部内容为未翻译',
  'translate_button_refresh' => '返回所有的修改',
  'translate_chk_autotranslate' => '自动更新类似翻译',
  'translate_panel_currentarea' => '现在的翻译',
  'translate_panel_globalarea' => '所有翻译',
  'translate_original_value' => '原始值 :',
  'translate_translated_value' => '你的翻译 :',
  'translate_chk_skiptranslated' => '跳过已翻译的线索',
)
?>