<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:47
  * By: anw
  * From: ro/_i18n/default/actions/action_translate/action_translate
  * Revision: 4455
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_translate/action_translate",
"rev" => "4455",
"time" => "1239219767",
"lang" => "ro",
);
$lang = array (
  'translate_explain' => 'Mod traducere :',
  'translate_explain_1' => 'Selecteaza o noua referinta de traducere : %selectref%',
  'translate_explain_2' => 'Apasa pe o fraza si scrie traducerea ta !',
  'translate_explain_3' => 'Apasa pe o alta fraza si tradu-o in acelasi mod',
  'translate_explain_4' => 'Cand ai terminat, salveaza-ti munca !',
  'translate_button_revert' => 'Refa',
  'translate_button_save' => 'Salveaza toate schimbarile',
  'translate_button_closepanel' => 'Inchide acest panou',
  'translate_chk_translated' => 'Marcheaza ca tradus',
  'translate_chk_apply' => 'Marcheaza ca netradus in toate celalalte limbi',
  'translate_button_doneall' => 'Marcheaza TOT ca tradus',
  'translate_button_undoneall' => 'Marcheaza TOT ca netradus',
  'translate_button_refresh' => 'Refa TOATE schimbarile',
  'translate_chk_autotranslate' => 'Auto-actualizeaza toate traducerile similare',
  'translate_panel_currentarea' => 'Traducere curenta',
  'translate_panel_globalarea' => 'Toate traducerile',
  'translate_original_value' => 'Valuare originala :',
  'translate_translated_value' => 'Traducerea ta :',
)
?>