<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: pl/_i18n/default/actions/action_translate/action_translate
  * Revision: 4452
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_translate/action_translate",
"rev" => "4452",
"time" => "1239219766",
"lang" => "pl",
);
$lang = array (
  'translate_explain' => 'Tryb tłumaczenia :',
  'translate_explain_1' => 'Zaznacz referencję tłumaczenia : %selectref%',
  'translate_explain_2' => 'Kliknij na frazę i wpisz swoje tłumaczenia !',
  'translate_explain_3' => 'Kliknij na inną frazę i przetłumacz tym samym sposobem',
  'translate_explain_4' => 'Kiedy skończysz, zapisz swoją pracę !',
  'translate_button_revert' => 'Cofnij',
  'translate_button_save' => 'Zapisz wszystkie zmiany',
  'translate_button_closepanel' => 'Zamknij ten panel',
  'translate_chk_translated' => 'Zaznacz jako przetłumaczone',
  'translate_chk_apply' => 'Zaznacz jako nieprzetłumaczone we wszystkich innych językach',
  'translate_button_doneall' => 'Zaznacz WSZYSTKO jako przetłumaczone',
  'translate_button_undoneall' => 'Zaznacz WSZYSTKO jako nieprzetłumaczone',
  'translate_button_refresh' => 'Cofnij WSZYSTKIE zmiany',
  'translate_chk_autotranslate' => 'Auto-aktualizacja zbliżonych tłumaczeń',
  'translate_panel_currentarea' => 'Obecne tłumaczenie',
  'translate_panel_globalarea' => 'Wszystkie tłumaczenia',
  'translate_original_value' => 'Treść orginalna :',
  'translate_translated_value' => 'Twoje tłumaczenie :',
  'translate_chk_skiptranslated' => 'Opuść przetłumaczone łańcuchy znaków',
)
?>