<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: de/_i18n/default/actions/action_translate/action_translate
  * Revision: 4446
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_translate/action_translate",
"rev" => "4446",
"time" => "1239219766",
"lang" => "de",
);
$lang = array (
  'translate_explain' => 'Übersetzungsmodus:',
  'translate_explain_1' => 'Wählen Sie eine Ausgangssprache zur Übersetzung: %selectref%',
  'translate_explain_2' => 'Klicken Sie auf einen Textblock und geben Sie Ihre Übersetzung ein!',
  'translate_explain_3' => 'Klicken Sie auf einen anderen Textblock und übersetzen Sie Ihn in gleicher Weise',
  'translate_explain_4' => 'Wenn Sie fertig sind, speichern Sie Ihre Arbeit!',
  'translate_button_revert' => 'Rückgängig',
  'translate_button_save' => 'Speichere alle Änderungen',
  'translate_button_closepanel' => 'Dieses Panel schließen',
  'translate_chk_translated' => 'Als übersetzt markieren',
  'translate_chk_apply' => 'Für alle anderen Sprachen als unübersetzt markieren',
  'translate_button_doneall' => 'ALLES als übersetzt markieren',
  'translate_button_undoneall' => 'ALLES als unübersetzt markieren',
  'translate_button_refresh' => 'ALLE Änderungen rückgängig machen',
  'translate_chk_autotranslate' => 'Automatisch ähnliche Übersetzungen anpassen',
  'translate_panel_currentarea' => 'Aktuelle Übersetzung',
  'translate_panel_globalarea' => 'Alle Übersetzungen',
  'translate_original_value' => 'Originaler Ausdruck:',
  'translate_translated_value' => 'Ihre Übersetzung:',
  'translate_chk_skiptranslated' => 'Überspringe Übersetztes',
)
?>