<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: fr/_i18n/default/actions/action_translate/action_translate
  * Revision: 4448
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_translate/action_translate",
"rev" => "4448",
"time" => "1239219766",
"lang" => "fr",
);
$lang = array (
  'translate_explain' => 'Processus de traduction :',
  'translate_explain_1' => 'Sélectionnez une langue de référence : %selectref%',
  'translate_explain_2' => 'Cliquez sur une phrase et saisissez votre traduction',
  'translate_explain_3' => 'Cliquez sur une autre phrase et traduisez la de la même manière',
  'translate_explain_4' => 'Une fois accompli, enregistrez votre travail !',
  'translate_button_revert' => 'Rétablir',
  'translate_button_save' => 'Enregistrer toutes les modifications',
  'translate_button_closepanel' => 'Fermer ce panneau',
  'translate_chk_translated' => 'Marquer comme traduit',
  'translate_chk_apply' => 'Marquer comme non traduit dans toutes les autres langues',
  'translate_button_doneall' => 'Marquer TOUT comme traduit',
  'translate_button_undoneall' => 'Marquer TOUT comme non traduit',
  'translate_button_refresh' => 'Annuler toutes les modifications',
  'translate_chk_autotranslate' => 'Mise à jour automatique des traductions similaires',
  'translate_panel_currentarea' => 'Traduction actuelle',
  'translate_panel_globalarea' => 'TOUTES les traductions',
  'translate_original_value' => 'Valeur originelle :',
  'translate_translated_value' => 'Votre traduction :',
  'translate_chk_skiptranslated' => 'Passer les traductions déjà effectuées',
)
?>