<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: it/_i18n/default/actions/action_translate/action_translate
  * Revision: 4450
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_translate/action_translate",
"rev" => "4450",
"time" => "1239219766",
"lang" => "it",
);
$lang = array (
  'translate_explain' => 'Modalità traduzione :',
  'translate_explain_1' => 'Seleziona la traduzione di riferimento : %selectref%',
  'translate_explain_2' => 'Clicca su una frase e digitane la traduzione !',
  'translate_explain_3' => 'Clicca su un\'altra frase e traducila nello stesso modo',
  'translate_explain_4' => 'Quando hai terminato, salva il tuo lavoro !',
  'translate_button_revert' => 'Ripristina',
  'translate_button_save' => 'Salva tutte le modifiche',
  'translate_button_closepanel' => 'Chiudi questo pannello',
  'translate_chk_translated' => 'Segna come tradotto',
  'translate_chk_apply' => 'Segna come da tradurre in tutte le altre lingue',
  'translate_button_doneall' => 'Segna TUTTO come tradotto',
  'translate_button_undoneall' => 'Segna TUTTO come da tradurre',
  'translate_button_refresh' => 'Ripristina TUTTE le modifiche',
  'translate_chk_autotranslate' => 'Aggiorna automaticamente le traduzioni simili',
  'translate_panel_currentarea' => 'Traduzione attuale',
  'translate_panel_globalarea' => 'Tutte le traduzioni',
  'translate_original_value' => 'Valore originale :',
  'translate_translated_value' => 'La tua traduzione :',
  'translate_chk_skiptranslated' => 'Salta le frasi tradotte',
)
?>