<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: ar/_i18n/default/actions/action_translate/action_translate
  * Revision: 4444
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_translate/action_translate",
"rev" => "4444",
"time" => "1239219766",
"lang" => "ar",
);
$lang = array (
  'translate_explain' => 'نمط الترجمة:',
  'translate_explain_1' => 'الرجاء إختيار مرجع عملية الترجمة: %selectref%',
  'translate_explain_2' => 'الرجاء النقر على عبارة أو جملة معينة و كتابة الترجمة الخاصة بها!',
  'translate_explain_3' => 'قم باختيار عبارة أخرى و ترجمها بنفس الطريقة',
  'translate_explain_4' => 'عند الإنتهاء الرجاء القيام بحفظ البيانات!',
  'translate_button_revert' => 'إرجاع',
  'translate_button_save' => 'حفظ جميع التغييرات',
  'translate_button_closepanel' => 'إغلاق هذا المقطع',
  'translate_chk_translated' => 'تأشير بأنها مترجمة',
  'translate_chk_apply' => 'تأشير بأنها غير مترجمة في كل اللغات الأخرى',
  'translate_button_doneall' => 'تأشير جميع المحتويات بأنها مترجمة',
  'translate_button_undoneall' => 'تأشير جميع المحتويات بأنها غير مترجمة',
  'translate_button_refresh' => 'الرجوع عن جميع التغيرات',
  'translate_chk_autotranslate' => 'ترجمة العبارات المشابهة بنفس الترجمة',
  'translate_panel_currentarea' => 'الترجمة الحالية',
  'translate_panel_globalarea' => 'جميع الترجمات',
  'translate_original_value' => 'العبارة الأصلية:',
  'translate_translated_value' => 'الترجمة بلغتك الخاصة:',
  'translate_chk_skiptranslated' => 'إقفز عن الكلمات أو العبارات المترجمة',
)
?>