<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3788
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3788",
"time" => "1239219819",
"lang" => "it",
);
$lang = array (
  'contentclass_trfile_label' => 'file i18n',
  'local_title' => 'File delle traduzioni : %name%',
  'local_explain' => 'Questa è una versione online di un file di traduzione.',
  'local_item_id' => 'ID della traduzione',
  'local_item_value' => 'Valore della Traduzione',
)
?>