<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: ro/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3792
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3792",
"time" => "1239219819",
"lang" => "ro",
);
$lang = array (
  'contentclass_trfile_label' => 'fisier i18n',
  'local_title' => 'Fisier traducere : %name%',
  'local_item_id' => 'ID traducere',
  'local_item_value' => 'Valuare traducere',
)
?>