<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3805
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3805",
"time" => "1239219819",
"lang" => "pl",
);
$lang = array (
  'contentfield_trfile_name_label' => 'Nazwa pliku',
  'contentfield_trfile_items_id_label' => 'ID tłumaczenia',
  'contentfield_trfile_items_value_label' => 'Wartość tłumaczenia',
)
?>