<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3789
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3789",
"time" => "1239219819",
"lang" => "pl",
);
$lang = array (
  'contentclass_trfile_label' => 'plik i18n',
  'local_title' => 'Plik tłumaczenia : %name%',
  'local_item_id' => 'ID tłumaczenia',
  'local_item_value' => 'Wartość tłumaczenia',
)
?>