<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3812
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3812",
"time" => "1239219819",
"lang" => "zh_CN",
);
$lang = array (
  'contentfield_trfile_name_label' => '文件名',
  'contentfield_trfile_items_id_label' => '翻译ID',
  'contentfield_trfile_items_value_label' => '翻译value',
)
?>