<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3783
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3783",
"time" => "1239219819",
"lang" => "de",
);
$lang = array (
  'contentclass_trfile_label' => 'i18n Datei',
  'local_title' => 'Zu überesetzende Datei: %name%',
  'local_explain' => 'Dies ist eine Online-Version einer Übersetzungsdatei.',
  'local_item_id' => 'Übersetzungs ID',
  'local_item_value' => 'Zu übersetzender Ausdruck',
)
?>