<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3796
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3796",
"time" => "1239219819",
"lang" => "zh_CN",
);
$lang = array (
  'contentclass_trfile_label' => 'i18n 文件',
  'local_title' => '翻译文件 : %name%',
  'local_item_id' => '翻译ID',
  'local_item_value' => '翻译value',
)
?>