<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3802
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3802",
"time" => "1239219819",
"lang" => "fr",
);
$lang = array (
  'contentfield_trfile_name_label' => 'Nom du fichier',
  'contentfield_trfile_items_id_label' => 'ID de la traduction',
  'contentfield_trfile_items_value_label' => 'Valeur de la traduction',
)
?>