<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3786
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3786",
"time" => "1239219819",
"lang" => "fr",
);
$lang = array (
  'contentclass_trfile_label' => 'Fichier de traduction',
  'local_title' => 'Fichier de traduction : %name%',
  'local_explain' => 'Ceci est une version en ligne d\'un fichier de traduction.',
  'local_item_id' => 'ID de la traduction',
  'local_item_value' => 'Valeur de la traduction',
)
?>