<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: ro/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3808
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3808",
"time" => "1239219819",
"lang" => "ro",
);
$lang = array (
  'contentfield_trfile_name_label' => 'Nume fisier',
  'contentfield_trfile_items_id_label' => 'ID traducere',
  'contentfield_trfile_items_value_label' => 'Valuare traducere',
)
?>