<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3804
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3804",
"time" => "1239219819",
"lang" => "it",
);
$lang = array (
  'contentfield_trfile_name_label' => 'Nome del File',
  'contentfield_trfile_items_id_label' => 'ID della traduzione',
  'contentfield_trfile_items_value_label' => 'Valore della Traduzione',
)
?>