<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3797
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3797",
"time" => "1239219819",
"lang" => "ar",
);
$lang = array (
  'contentfield_trfile_name_label' => 'إسم الملف',
  'contentfield_trfile_items_id_label' => 'معرف الترجمة',
  'contentfield_trfile_items_value_label' => 'قيمة الترجمة النصية',
)
?>