<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields
  * Revision: 3799
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile-contentfields",
"rev" => "3799",
"time" => "1239219819",
"lang" => "de",
);
$lang = array (
  'contentfield_trfile_name_label' => 'Dateiname',
  'contentfield_trfile_items_id_label' => 'Übersetzungs ID',
  'contentfield_trfile_items_value_label' => 'Zu übersetzender Ausdruck',
)
?>