<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile
  * Revision: 3781
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_trfile/contentclass_trfile",
"rev" => "3781",
"time" => "1239219819",
"lang" => "ar",
);
$lang = array (
  'contentclass_trfile_label' => 'i18n file',
  'local_title' => 'ملف الترجمة: %name%',
  'local_item_id' => 'معرف الترجمة',
  'local_item_value' => 'قيمة الترجمة النصية',
)
?>