<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields
  * Revision: 3701
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields",
"rev" => "3701",
"time" => "1239219818",
"lang" => "ar",
);
$lang = array (
  'contentfield_news_intro_label' => 'مقدمة الخبر',
  'contentfield_news_body_label' => 'تفاصيل الخبرر',
  'contentfield_news_title_label' => 'عنوان الخبر',
  'contentfield_news_date_label' => 'تاريخ الخبر',
)
?>