<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_news/contentclass_news
  * Revision: 3685
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_news/contentclass_news",
"rev" => "3685",
"time" => "1239219818",
"lang" => "ar",
);
$lang = array (
  'contentclass_news_label' => 'الأخبار',
  'local_news_date' => 'نشر في %date%',
)
?>