<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields
  * Revision: 3709
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields",
"rev" => "3709",
"time" => "1239219818",
"lang" => "pl",
);
$lang = array (
  'contentfield_news_intro_label' => 'Wstęp',
  'contentfield_news_body_label' => 'Rozwinięcie',
  'contentfield_news_title_label' => 'Tytuł wiadomości',
  'contentfield_news_date_label' => 'Data wiadomości',
)
?>