<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_news/contentclass_news
  * Revision: 3692
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_news/contentclass_news",
"rev" => "3692",
"time" => "1239219818",
"lang" => "it",
);
$lang = array (
  'contentclass_news_label' => 'Novità',
  'local_news_date' => 'Pubblicato il %date%',
)
?>