<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_news/contentclass_news
  * Revision: 3700
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_news/contentclass_news",
"rev" => "3700",
"time" => "1239219818",
"lang" => "zh_CN",
);
$lang = array (
  'contentclass_news_label' => '新闻',
  'local_news_date' => '发布时间 %date%',
)
?>