<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields
  * Revision: 3708
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields",
"rev" => "3708",
"time" => "1239219818",
"lang" => "it",
);
$lang = array (
  'contentfield_news_intro_label' => 'Introduzione alle novità',
  'contentfield_news_body_label' => 'Corpo delle Novità',
  'contentfield_news_title_label' => 'Titolo delle Novità',
  'contentfield_news_date_label' => 'Data delle Novità',
)
?>