<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields
  * Revision: 3716
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields",
"rev" => "3716",
"time" => "1239219818",
"lang" => "zh_CN",
);
$lang = array (
  'contentfield_news_intro_label' => '新闻简介',
  'contentfield_news_body_label' => '新闻主体',
  'contentfield_news_title_label' => '新闻标题',
  'contentfield_news_date_label' => '新闻日期',
)
?>