<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_news/contentclass_news
  * Revision: 3690
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_news/contentclass_news",
"rev" => "3690",
"time" => "1239219818",
"lang" => "fr",
);
$lang = array (
  'contentclass_news_label' => 'Actualités',
  'local_news_date' => 'Publié le %date%',
)
?>