<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields
  * Revision: 3706
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields",
"rev" => "3706",
"time" => "1239219818",
"lang" => "fr",
);
$lang = array (
  'contentfield_news_intro_label' => 'Intro des actualités',
  'contentfield_news_body_label' => 'Corps des actualités',
  'contentfield_news_title_label' => 'Titre des actualités',
  'contentfield_news_date_label' => 'Date des actualités',
)
?>