<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_news/contentclass_news
  * Revision: 3693
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_news/contentclass_news",
"rev" => "3693",
"time" => "1239219818",
"lang" => "pl",
);
$lang = array (
  'contentclass_news_label' => 'Wiadomości',
  'local_news_date' => 'Opublikowano %date%',
)
?>