<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_news/contentclass_news
  * Revision: 3687
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_news/contentclass_news",
"rev" => "3687",
"time" => "1239219818",
"lang" => "de",
);
$lang = array (
  'contentclass_news_label' => 'News',
  'local_news_date' => 'Veröffentlicht am %date%',
)
?>