<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields
  * Revision: 3703
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_news/contentclass_news-contentfields",
"rev" => "3703",
"time" => "1239219818",
"lang" => "de",
);
$lang = array (
  'contentfield_news_intro_label' => 'News Einführung',
  'contentfield_news_body_label' => 'News Hauptteil',
  'contentfield_news_title_label' => 'News Titel',
  'contentfield_news_date_label' => 'News Datum',
)
?>