<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_newtranslation/action_newtranslation
  * Revision: 3444
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_newtranslation/action_newtranslation",
"rev" => "3444",
"time" => "1239219762",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '对 %pagename% 的新翻译',
)
?>