<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: fr/_i18n/default/actions/action_newtranslation/action_newtranslation
  * Revision: 3434
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_newtranslation/action_newtranslation",
"rev" => "3434",
"time" => "1239219762",
"lang" => "fr",
);
$lang = array (
  'title' => 'Nouvelle traduction pour %pagename%',
)
?>