<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: de/_i18n/default/actions/action_newtranslation/action_newtranslation
  * Revision: 3431
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_newtranslation/action_newtranslation",
"rev" => "3431",
"time" => "1239219762",
"lang" => "de",
);
$lang = array (
  'title' => 'Neue Übersetzung für %pagename%',
)
?>