<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: pl/_i18n/default/actions/action_newtranslation/action_newtranslation
  * Revision: 3437
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_newtranslation/action_newtranslation",
"rev" => "3437",
"time" => "1239219762",
"lang" => "pl",
);
$lang = array (
  'title' => 'Nowe tłumaczenie dla %pagename%',
)
?>