<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: it/_i18n/default/actions/action_newtranslation/action_newtranslation
  * Revision: 3436
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_newtranslation/action_newtranslation",
"rev" => "3436",
"time" => "1239219762",
"lang" => "it",
);
$lang = array (
  'title' => 'Nuova tradudione per %pagename%',
)
?>