<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: ar/_i18n/default/actions/action_newtranslation/action_newtranslation
  * Revision: 3429
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_newtranslation/action_newtranslation",
"rev" => "3429",
"time" => "1239219762",
"lang" => "ar",
);
$lang = array (
  'title' => 'ترجمة جديدة للصفحة %pagename%',
)
?>