<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: it/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3548
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3548",
"time" => "1239219765",
"lang" => "it",
);
$lang = array (
  'naventry' => 'Mappa del sito',
)
?>