<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: ro/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3552
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3552",
"time" => "1239219765",
"lang" => "ro",
);
$lang = array (
  'naventry' => 'Harta site-ului',
)
?>