<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: fr/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3546
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3546",
"time" => "1239219765",
"lang" => "fr",
);
$lang = array (
  'naventry' => 'Plan du site',
)
?>