<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: de/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3543
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3543",
"time" => "1239219765",
"lang" => "de",
);
$lang = array (
  'naventry' => 'Seitenübersicht',
)
?>