<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3556
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3556",
"time" => "1239219765",
"lang" => "zh_CN",
);
$lang = array (
  'naventry' => '网站地图',
)
?>