<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: ar/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3541
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3541",
"time" => "1239219765",
"lang" => "ar",
);
$lang = array (
  'naventry' => 'خارطة الموقع',
)
?>