<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:45
  * By: anw
  * From: pl/_i18n/default/actions/action_sitemap/action_sitemap
  * Revision: 3549
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_sitemap/action_sitemap",
"rev" => "3549",
"time" => "1239219765",
"lang" => "pl",
);
$lang = array (
  'naventry' => 'Mapa witryny',
)
?>