<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: fr/_i18n/default/actions/action_edit/action_edit
  * Revision: 3258
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_edit/action_edit",
"rev" => "3258",
"time" => "1239219762",
"lang" => "fr",
);
$lang = array (
  'title' => 'Modification de %pagename%',
  'publish' => 'Publier',
  'preview' => 'Aperçu',
  'savenewdraft' => 'Enregistrer la nouvelle ébauche',
  'updatedraft' => 'Mettre à jour la nouvelle ébauche',
  'discarddraft' => 'Jeter l\'ébauche',
  'discarddraft_alert' => 'Ceci va supprimer définitivement l\'ébauche sur laquelle vous travaillez. Poursuivre ?',
  'drafts' => 'Ébauche :',
  'draftlist' => 'Des ébauches sont en suspens pour cette page. Cliquez sur une ébauche pour la reprendre, puis publiez-la.',
  'nodrafts' => 'Il n\'y a aucune ébauche pour cette page',
  'preview_title' => 'Aperçu',
)
?>