<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: it/_i18n/default/actions/action_edit/action_edit
  * Revision: 3260
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_edit/action_edit",
"rev" => "3260",
"time" => "1239219762",
"lang" => "it",
);
$lang = array (
  'title' => 'Stai modificando %pagename%',
  'publish' => 'Pubblica',
  'preview' => 'Anteprima',
  'savenewdraft' => 'Salva la nuova bozza',
  'updatedraft' => 'Aggiorna la bozza',
  'discarddraft' => 'Annulla la bozza',
  'discarddraft_alert' => 'Questo eliminerà per sempre la bozza su cui stai lavorando. Continuo ?',
  'drafts' => 'Bozza :',
  'draftlist' => 'Esistono delle bozze in attesa per questa pagina. Clicca su una di esse per ripristinarla e pubblicala.',
  'nodrafts' => 'Non ci sono bozze per questa pagina',
  'preview_title' => 'Anteprima',
)
?>