<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: pl/_i18n/default/actions/action_edit/action_edit
  * Revision: 3261
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_edit/action_edit",
"rev" => "3261",
"time" => "1239219762",
"lang" => "pl",
);
$lang = array (
  'title' => 'Edytuj %pagename%',
  'publish' => 'Publikuj',
  'preview' => 'Podgląd',
  'savenewdraft' => 'Zapisz nowy szkic',
  'updatedraft' => 'Aktualizuj szkic',
  'discarddraft' => 'Porzucanie szkicu',
  'discarddraft_alert' => 'To spowoduje permanentne skasowanie szkicu nad którym pracujesz. Kontynuować ?',
  'drafts' => 'Szkic :',
  'draftlist' => 'To są oczekujące szkice dla tej strony. Kliknij na szkic by kontynuować, a następnie go opublikować.',
  'nodrafts' => 'Nie ma szkiców dla tej strony',
  'preview_title' => 'Podgląd',
)
?>