<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_edit/action_edit
  * Revision: 3268
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_edit/action_edit",
"rev" => "3268",
"time" => "1239219762",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '编辑 %pagename%',
  'publish' => '发布',
  'preview' => '预览',
  'savenewdraft' => '保存新草稿',
  'updatedraft' => '更新草稿',
  'discarddraft' => '放弃草稿',
  'discarddraft_alert' => '这将会永久地删除你正在编辑中的草稿,继续吗 ?',
  'drafts' => '草稿 :',
  'draftlist' => '这些是这个页面的待决草稿,点击一个草稿恢复它,然后发布它',
  'nodrafts' => '这个页面没有草稿',
  'preview_title' => '预览',
)
?>