<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: ar/_i18n/default/actions/action_edit/action_edit
  * Revision: 3253
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_edit/action_edit",
"rev" => "3253",
"time" => "1239219762",
"lang" => "ar",
);
$lang = array (
  'title' => 'تعديل الصفحة %pagename%',
  'publish' => 'نشر',
  'preview' => 'العرض الأولي',
  'savenewdraft' => 'حفظ مسودة جديدة',
  'updatedraft' => 'تعديل مسودة',
  'discarddraft' => 'إلغاء مسودة',
  'discarddraft_alert' => 'ستقوم بحذف المسودة اللتي تعمل عليها بشكل نهائي، هل توافق على ذلك؟',
  'drafts' => 'مسودة:',
  'draftlist' => 'هناك مسودات أخرى خاصة بهذه الصفحة، أنقر إحدى المسودات لتعديلها ومن ثم نشرها.',
  'nodrafts' => 'لا يوجد مسودات خاصة بهذه الصفحة',
  'preview_title' => 'العرض الأولي',
)
?>