<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:42
  * By: anw
  * From: de/_i18n/default/actions/action_edit/action_edit
  * Revision: 3255
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_edit/action_edit",
"rev" => "3255",
"time" => "1239219762",
"lang" => "de",
);
$lang = array (
  'title' => 'Editiere %pagename%',
  'publish' => 'Veröffentlichen',
  'preview' => 'Vorschau',
  'savenewdraft' => 'Neue Vorlage speichern',
  'updatedraft' => 'Vorlage aktualisieren',
  'discarddraft' => 'Vorlage verwerfen',
  'discarddraft_alert' => 'Dies wird die Vorlage an der Sie arbeiten dauerhaft löschen. Fortsetzen?',
  'drafts' => 'Vorlage :',
  'draftlist' => 'Es existieren angefangene Vorlagen für diese Seite. Klicken Sie auf eine Vorlage, um diese fortzusetzen und dann zu veröffentlichen.',
  'nodrafts' => 'Es existieren keine Vorlagen für diese Seite',
  'preview_title' => 'Vorschau',
)
?>