<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: it/_i18n/default/actions/action_settings/action_settings
  * Revision: 3532
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_settings/action_settings",
"rev" => "3532",
"time" => "1239219763",
"lang" => "it",
);
$lang = array (
  'title' => 'Impostazioni',
  'settings_lang' => 'Lingua dell\'interfaccia',
  'settings_timezone' => 'Time zone',
  'settings_prefs_t' => 'Preferenze',
  'settings_currentpassword' => 'Password attuale',
  'settings_newpassword' => 'Nuova password',
  'settings_newpassword_repeat' => 'Nuova password (ripeti)',
  'settings_changepassword' => 'Cambia la password',
  'settings_cancelpassword' => 'Annulla il cambiamento della password',
  'settings_account_t' => 'Impostazioni dell\'account',
  'settings_account_edit' => 'Puoi aggiornare le impostazioni del tuo account %startlink%cliccando qui%endlink%',
  'settings_submit' => 'Salva le impostazioni',
  'settings_updated' => 'Le tue impostazioni sono state aggiornate',
  'err_badnewpassword' => 'La nuova password non è consentita',
)
?>