<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: pl/_i18n/default/actions/action_settings/action_settings
  * Revision: 3533
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_settings/action_settings",
"rev" => "3533",
"time" => "1239219763",
"lang" => "pl",
);
$lang = array (
  'title' => 'Ustawienia',
  'settings_lang' => 'Język interfejsu',
  'settings_timezone' => 'Strefa czasowa',
  'settings_prefs_t' => 'Preferencje',
  'settings_newpassword' => 'Nowe hasło',
  'settings_newpassword_repeat' => 'Nowe hasło  (powtórz)',
  'settings_changepassword' => 'Zmień hasło',
  'settings_cancelpassword' => 'Zrezygnuj ze zmiany hasła',
  'settings_account_t' => 'Ustawienia konta',
  'settings_account_edit' => 'Możesz uaktualnić ustawienia swojego konta %startlink%klikając tutaj%endlink%',
  'settings_submit' => 'Zapisz ustawienia',
  'settings_updated' => 'Twoje ustawienia zostały uaktualnione',
)
?>