<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_settings/action_settings
  * Revision: 3540
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_settings/action_settings",
"rev" => "3540",
"time" => "1239219763",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '设定',
  'settings_lang' => '界面语言',
  'settings_timezone' => '时区',
  'settings_prefs_t' => '偏好设定',
  'settings_newpassword' => '新密码',
  'settings_newpassword_repeat' => '新密码 (重复)',
  'settings_changepassword' => '改变密码',
  'settings_cancelpassword' => '取消改变密码',
  'settings_account_t' => '帐户设定',
  'settings_account_edit' => '你可以%startlink%点击这里%endlink%更新你的帐户设定',
  'settings_submit' => '保存设定',
  'settings_updated' => '你的设定已被更新',
)
?>