<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: ar/_i18n/default/actions/action_settings/action_settings
  * Revision: 3525
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_settings/action_settings",
"rev" => "3525",
"time" => "1239219763",
"lang" => "ar",
);
$lang = array (
  'title' => 'الإعدادات',
  'settings_lang' => 'لغة الواجهة',
  'settings_timezone' => 'منطقة التوقيت',
  'settings_prefs_t' => 'التفضيلات',
  'settings_newpassword' => 'كلمة السر الجديدة',
  'settings_newpassword_repeat' => 'تأكيد كلمة السر الجديدة',
  'settings_changepassword' => 'تغيير كلمة السر',
  'settings_cancelpassword' => 'إلغاء تغيير كلمة السر',
  'settings_account_t' => 'إعدادات الحساب',
  'settings_account_edit' => 'يمكنك تعديل إعدادات حسابك عن طريق  %startlink%النقر هنا%endlink%',
  'settings_submit' => 'حفظ الإعدادات',
  'settings_updated' => 'لقد تم تعديل إعداداتك',
)
?>