<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: ro/_i18n/default/actions/action_settings/action_settings
  * Revision: 3536
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_settings/action_settings",
"rev" => "3536",
"time" => "1239219763",
"lang" => "ro",
);
$lang = array (
  'title' => 'Setari',
  'settings_lang' => 'Limba interfata',
  'settings_timezone' => 'Fus orar',
  'settings_prefs_t' => 'Preferinte',
  'settings_account_t' => 'Setari cont',
  'settings_account_edit' => 'Poti sa iti modifici setarile contului %startlink%facand un click aici%endlink%',
  'settings_submit' => 'Salveaza setari',
  'settings_updated' => 'Setarile tale au fost actualizate',
)
?>