<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: fr/_i18n/default/actions/action_settings/action_settings
  * Revision: 3530
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_settings/action_settings",
"rev" => "3530",
"time" => "1239219763",
"lang" => "fr",
);
$lang = array (
  'title' => 'Paramètres',
  'settings_lang' => 'Langue de l\'interface',
  'settings_timezone' => 'Fuseau horaire',
  'settings_prefs_t' => 'Préférences',
  'settings_currentpassword' => 'Mot de passe actuel',
  'settings_newpassword' => 'Nouveau mot de passe',
  'settings_newpassword_repeat' => 'Nouveau mot de passe (vérification)',
  'settings_changepassword' => 'Changer de mot de passe',
  'settings_cancelpassword' => 'Annuler le changement de mot de passe',
  'settings_account_t' => 'Paramètres du compte',
  'settings_account_edit' => 'Vous pouvez mettre à jour les paramètres de votre compte %startlink%en cliquant ici%endlink%',
  'settings_submit' => 'Enregistrer vos paramètres',
  'settings_updated' => 'Vos paramètres ont été mis à jour',
  'err_badnewpassword' => 'Nouveau mot de passe non valide',
)
?>