<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: de/_i18n/default/actions/action_settings/action_settings
  * Revision: 3527
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_settings/action_settings",
"rev" => "3527",
"time" => "1239219763",
"lang" => "de",
);
$lang = array (
  'title' => 'Einstellungen',
  'settings_lang' => 'Sprache der Benutzeroberfläche',
  'settings_timezone' => 'Zeitzone',
  'settings_prefs_t' => 'Optionen',
  'settings_currentpassword' => 'Aktuelles Passwort',
  'settings_newpassword' => 'Neues Passwort',
  'settings_newpassword_repeat' => 'Neues Passwort (Wiederholung)',
  'settings_changepassword' => 'Passwort ändern',
  'settings_cancelpassword' => 'Passwortänderung abbrechen',
  'settings_account_t' => 'Account Konfiguration',
  'settings_account_edit' => 'Sie können Ihre Account Einstellungen aktualisieren indem Sie %startlink%hier klicken%endlink%',
  'settings_submit' => 'Einstellungen speichern',
  'settings_updated' => 'Ihre Einstellungen wurden aktualisiert',
  'err_badnewpassword' => 'Unerlaubtes neues Passwort',
)
?>