<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: ro/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3760
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3760",
"time" => "1239219818",
"lang" => "ro",
);
$lang = array (
  'contentclass_page_label' => 'Pagina',
)
?>