<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3764
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3764",
"time" => "1239219818",
"lang" => "zh_CN",
);
$lang = array (
  'contentclass_page_label' => 'Page',
)
?>