<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3751
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3751",
"time" => "1239219818",
"lang" => "de",
);
$lang = array (
  'contentclass_page_label' => 'Seite',
)
?>