<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3756
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3756",
"time" => "1239219818",
"lang" => "it",
);
$lang = array (
  'contentclass_page_label' => 'Pagina',
)
?>