<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3749
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3749",
"time" => "1239219818",
"lang" => "ar",
);
$lang = array (
  'contentclass_page_label' => 'الصفحة',
)
?>