<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3757
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3757",
"time" => "1239219818",
"lang" => "pl",
);
$lang = array (
  'contentclass_page_label' => 'Strona',
)
?>