<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:38
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_page/contentclass_page
  * Revision: 3754
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_page/contentclass_page",
"rev" => "3754",
"time" => "1239219818",
"lang" => "fr",
);
$lang = array (
  'contentclass_page_label' => 'Page',
)
?>