<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_menu/contentclass_menu
  * Revision: 3660
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_menu/contentclass_menu",
"rev" => "3660",
"time" => "1239219819",
"lang" => "it",
);
$lang = array (
  'contentclass_menu_label' => 'Menu',
)
?>