<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_menu/contentclass_menu
  * Revision: 3653
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_menu/contentclass_menu",
"rev" => "3653",
"time" => "1239219819",
"lang" => "ar",
);
$lang = array (
  'contentclass_menu_label' => 'القائمة',
)
?>