<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: pl/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields
  * Revision: 3677
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields",
"rev" => "3677",
"time" => "1239219819",
"lang" => "pl",
);
$lang = array (
  'contentfield_menu_title_label' => 'Tytuł menu',
  'contentfield_menu_items_label' => 'Punkty menu',
  'contentfield_menu_items_single' => 'punkt menu',
  'contentfield_menuItem_mainlink_label' => 'Głowny link',
)
?>