<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: it/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields
  * Revision: 3676
  */
$anwiki_build = array(
"from" => "it/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields",
"rev" => "3676",
"time" => "1239219819",
"lang" => "it",
);
$lang = array (
  'contentfield_menu_title_label' => 'Titolo del Menu',
  'contentfield_menu_items_label' => 'Oggetti del Menu',
  'contentfield_menu_items_single' => 'oggetto del Menu',
  'contentfield_menuItem_mainlink_label' => 'Collegamento primcipale',
  'contentfield_menuItem_subitems_label' => 'Sotto menu',
  'contentfield_menuItem_subitems_single' => 'sotto menu',
  'contentfield_menuItem_urlmatches_label' => 'Gli URL attivi corrispondono (regexp o URL)',
  'contentfield_menuItem_urlmatches_single' => 'l\'URL attivo corrisponde',
  'contentfield_menuSubItem_link_label' => 'Sotto collegamento',
  'contentfield_menuSubItem_urlmatches_label' => 'Gli URL attivi corrispondono (regexp o URL)',
  'contentfield_menuSubItem_urlmatches_single' => 'l\'URL attivo corrisponde (regexp o URL)',
)
?>