<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields
  * Revision: 3684
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields",
"rev" => "3684",
"time" => "1239219819",
"lang" => "zh_CN",
);
$lang = array (
  'contentfield_menu_title_label' => '菜单标题',
  'contentfield_menu_items_label' => '菜单组件',
  'contentfield_menu_items_single' => '菜单组件',
  'contentfield_menuItem_mainlink_label' => '菜单连接',
)
?>