<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields
  * Revision: 3674
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields",
"rev" => "3674",
"time" => "1239219819",
"lang" => "fr",
);
$lang = array (
  'contentfield_menu_title_label' => 'Titre du menu',
  'contentfield_menu_items_label' => 'Éléments du menu',
  'contentfield_menu_items_single' => 'élément du menu',
  'contentfield_menuItem_mainlink_label' => 'Lien principal',
  'contentfield_menuItem_subitems_label' => 'Menus secondaires',
  'contentfield_menuItem_subitems_single' => 'menu secondaire',
  'contentfield_menuItem_urlmatches_label' => 'Correspondances d\'URL actives (regexp ou URL)',
  'contentfield_menuItem_urlmatches_single' => 'correspondance d\'URL active',
  'contentfield_menuSubItem_link_label' => 'lien secondaire',
  'contentfield_menuSubItem_urlmatches_label' => 'Correspondances d\'URL actives (regexp ou URL)',
  'contentfield_menuSubItem_urlmatches_single' => 'correspondance d\'URL active (regexp ou URL)',
)
?>