<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: zh_CN/_i18n/default/contentclasses/contentclass_menu/contentclass_menu
  * Revision: 3668
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/contentclasses/contentclass_menu/contentclass_menu",
"rev" => "3668",
"time" => "1239219819",
"lang" => "zh_CN",
);
$lang = array (
  'contentclass_menu_label' => '菜单',
)
?>