<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: fr/_i18n/default/contentclasses/contentclass_menu/contentclass_menu
  * Revision: 3658
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/contentclasses/contentclass_menu/contentclass_menu",
"rev" => "3658",
"time" => "1239219819",
"lang" => "fr",
);
$lang = array (
  'contentclass_menu_label' => 'Menu',
)
?>