<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields
  * Revision: 3671
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields",
"rev" => "3671",
"time" => "1239219819",
"lang" => "de",
);
$lang = array (
  'contentfield_menu_title_label' => 'Menü Titel',
  'contentfield_menu_items_label' => 'Menü Objekte',
  'contentfield_menu_items_single' => 'Menü Objekt',
  'contentfield_menuItem_mainlink_label' => 'Hauptlink',
  'contentfield_menuItem_subitems_label' => 'Untermenüs',
  'contentfield_menuItem_subitems_single' => 'Untermenü',
  'contentfield_menuItem_urlmatches_label' => 'Active URL stimmt überein (regexp oder URL)',
  'contentfield_menuItem_urlmatches_single' => 'Aktive URL stimmt überein',
  'contentfield_menuSubItem_link_label' => 'Unterlink',
  'contentfield_menuSubItem_urlmatches_label' => 'Active URL stimmt überein (regexp oder URL)',
  'contentfield_menuSubItem_urlmatches_single' => 'Aktive URL stimmt überein (regexp oder URL)',
)
?>