<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: de/_i18n/default/contentclasses/contentclass_menu/contentclass_menu
  * Revision: 3655
  */
$anwiki_build = array(
"from" => "de/_i18n/default/contentclasses/contentclass_menu/contentclass_menu",
"rev" => "3655",
"time" => "1239219819",
"lang" => "de",
);
$lang = array (
  'contentclass_menu_label' => 'Menü',
)
?>