<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:43:39
  * By: anw
  * From: ar/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields
  * Revision: 3669
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/contentclasses/contentclass_menu/contentclass_menu-contentfields",
"rev" => "3669",
"time" => "1239219819",
"lang" => "ar",
);
$lang = array (
  'contentfield_menu_title_label' => 'عنوان القائمة',
  'contentfield_menu_items_label' => 'محتويات القائمة',
  'contentfield_menu_items_single' => 'محتوى القائمة',
  'contentfield_menuItem_mainlink_label' => 'الرابط الرئيسي',
)
?>