<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: fr/_i18n/default/actions/action_create/action_create
  * Revision: 3194
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_create/action_create",
"rev" => "3194",
"time" => "1239219764",
"lang" => "fr",
);
$lang = array (
  'title' => 'Créer une nouvelle page : %pagename%',
)
?>