<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: ar/_i18n/default/actions/action_create/action_create
  * Revision: 3189
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_create/action_create",
"rev" => "3189",
"time" => "1239219764",
"lang" => "ar",
);
$lang = array (
  'title' => 'أنشأ صفحة جديدة بإسم: %pagename%',
)
?>