<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_create/action_create
  * Revision: 3204
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_create/action_create",
"rev" => "3204",
"time" => "1239219764",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '创建一个新页面: %pagename%',
)
?>