<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: de/_i18n/default/actions/action_create/action_create
  * Revision: 3191
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_create/action_create",
"rev" => "3191",
"time" => "1239219764",
"lang" => "de",
);
$lang = array (
  'title' => 'Eine neue Seite erstellen: %pagename%',
)
?>