<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: it/_i18n/default/actions/action_create/action_create
  * Revision: 3196
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_create/action_create",
"rev" => "3196",
"time" => "1239219764",
"lang" => "it",
);
$lang = array (
  'title' => 'Crea una nuova pagina : %pagename%',
)
?>