<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:44
  * By: anw
  * From: pl/_i18n/default/actions/action_create/action_create
  * Revision: 3197
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_create/action_create",
"rev" => "3197",
"time" => "1239219764",
"lang" => "pl",
);
$lang = array (
  'title' => 'Tworzenie nowej strony : %pagename%',
)
?>