<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: it/_i18n/default/actions/action_diff/action_diff
  * Revision: 4399
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_diff/action_diff",
"rev" => "4399",
"time" => "1239219763",
"lang" => "it",
);
$lang = array (
  'title' => 'Differenze : %pagename%',
  'notice_same' => 'Stai confrontando una versione con se stessa, non vedrai alcuna differenza',
  'rev_current' => '(attuale)',
  'select_from' => 'Da :',
  'select_to' => 'A :',
  'submit' => 'mostra le differenze',
)
?>