<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: ar/_i18n/default/actions/action_diff/action_diff
  * Revision: 4393
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_diff/action_diff",
"rev" => "4393",
"time" => "1239219763",
"lang" => "ar",
);
$lang = array (
  'title' => 'الإختلافات: %pagename%',
  'notice_same' => 'أنت تقوم بمقارنة النسخة بنفسها لذلك فإنك لن تلاحظ وجود أي إختلافات',
  'rev_current' => '(الحالي)',
  'select_from' => 'من:',
  'select_to' => 'إلى:',
  'submit' => 'أظهر الإختلافات',
)
?>