<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: fr/_i18n/default/actions/action_diff/action_diff
  * Revision: 4397
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_diff/action_diff",
"rev" => "4397",
"time" => "1239219763",
"lang" => "fr",
);
$lang = array (
  'title' => 'Différences : %pagename%',
  'notice_same' => 'Vous comparez une révision à elle-même, vous ne verrez aucune différence',
  'rev_current' => '(actuel)',
  'select_from' => 'De :',
  'select_to' => 'À :',
  'submit' => 'afficher les différences',
)
?>