<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: ro/_i18n/default/actions/action_diff/action_diff
  * Revision: 4404
  */
$anwiki_build = array(
"from" => "ro/_i18n/default/actions/action_diff/action_diff",
"rev" => "4404",
"time" => "1239219763",
"lang" => "ro",
);
$lang = array (
  'title' => 'Diferente : %pagename%',
  'notice_same' => 'Compari o revizie cu ea insesi, nu vei vedea nici o diferenta',
  'rev_current' => '(curent)',
  'select_from' => 'De la :',
  'select_to' => 'La :',
  'submit' => 'arata diferente',
)
?>