<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_diff/action_diff
  * Revision: 4408
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_diff/action_diff",
"rev" => "4408",
"time" => "1239219763",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '区别 : %pagename%',
  'notice_same' => '你正在对比对它自己的校对版本, 你不会看到任何区别',
  'rev_current' => '(现在)',
  'select_from' => '从 :',
  'select_to' => '到 :',
  'submit' => '显示区别',
)
?>