<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: pl/_i18n/default/actions/action_diff/action_diff
  * Revision: 4401
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_diff/action_diff",
"rev" => "4401",
"time" => "1239219763",
"lang" => "pl",
);
$lang = array (
  'title' => 'Różnice : %pagename%',
  'notice_same' => 'Porównujesz korektę do tego, nie zobaczysz jakiejkolwiek różnicy',
  'rev_current' => '(obecnie)',
  'select_from' => 'Od :',
  'select_to' => 'Do :',
  'submit' => 'pokaż różnice',
)
?>