<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:43
  * By: anw
  * From: de/_i18n/default/actions/action_diff/action_diff
  * Revision: 4395
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_diff/action_diff",
"rev" => "4395",
"time" => "1239219763",
"lang" => "de",
);
$lang = array (
  'title' => 'Unterschiede: %pagename%',
  'notice_same' => 'Sie vergleichen eine Version mit sich selber, so dass Sie keine Unterschiede sehen werden',
  'rev_current' => '(aktuell)',
  'select_from' => 'Von :',
  'select_to' => 'An :',
  'submit' => 'Zeige Unterschiede',
)
?>