<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: pl/_i18n/default/actions/action_newtranslations/action_newtranslations
  * Revision: 3453
  */
$anwiki_build = array(
"from" => "pl/_i18n/default/actions/action_newtranslations/action_newtranslations",
"rev" => "3453",
"time" => "1239219766",
"lang" => "pl",
);
$lang = array (
  'title' => 'Wielokrotne tworzenie tłumaczeń',
  'addlang' => 'Tworzenie nowego tłumaczenia w...',
  'explain' => 'Możesz stworzyć następujące nowe tłumaczenia w %lang%',
  'created' => 'Następujące tłumaczenia zostały stworzone',
  'notranslation' => 'Żadne już więcej tłumaczenia, nie mogą być utworzone dla tego języka',
)
?>