<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: fr/_i18n/default/actions/action_newtranslations/action_newtranslations
  * Revision: 3450
  */
$anwiki_build = array(
"from" => "fr/_i18n/default/actions/action_newtranslations/action_newtranslations",
"rev" => "3450",
"time" => "1239219766",
"lang" => "fr",
);
$lang = array (
  'title' => 'Création de plusieurs traductions',
  'addlang' => 'Créer une nouvelle traduction en…',
  'explain' => 'Vous pouvez créer la traduction suivante en %lang%',
  'created' => 'Les traductions suivantes ont été créées',
  'notranslation' => 'Plus aucune traduction ne peut être créée dans cette langue',
)
?>