<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: ar/_i18n/default/actions/action_newtranslations/action_newtranslations
  * Revision: 3445
  */
$anwiki_build = array(
"from" => "ar/_i18n/default/actions/action_newtranslations/action_newtranslations",
"rev" => "3445",
"time" => "1239219766",
"lang" => "ar",
);
$lang = array (
  'title' => 'البدأ بعملية ترجمة متعددة الترجمات',
  'addlang' => 'بدأ الترجمات الجديدة في ...',
  'explain' => 'يمكنك البدأ بعمليات الترجمة الجديدة التالية بلغة %lang%',
  'created' => 'تم إنشاء الترجمات التالية',
  'notranslation' => 'لا يوجد ترجمات أخرى يمكن إنشاءها لهذه اللغة',
)
?>