<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: de/_i18n/default/actions/action_newtranslations/action_newtranslations
  * Revision: 3447
  */
$anwiki_build = array(
"from" => "de/_i18n/default/actions/action_newtranslations/action_newtranslations",
"rev" => "3447",
"time" => "1239219766",
"lang" => "de",
);
$lang = array (
  'title' => 'Mehrere Übersetzungen erstellen',
  'addlang' => 'Erstelle neue Übersetzung in...',
  'explain' => 'Sie können folgende, neue Übersetzung in %lang% erstellen',
  'created' => 'Die folgenden Übersetzungen wurden erstellt',
  'notranslation' => 'Es können für diese Sprache keine Übersetzungen mehr erstellt werden',
)
?>