<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: zh_CN/_i18n/default/actions/action_newtranslations/action_newtranslations
  * Revision: 3460
  */
$anwiki_build = array(
"from" => "zh_CN/_i18n/default/actions/action_newtranslations/action_newtranslations",
"rev" => "3460",
"time" => "1239219766",
"lang" => "zh_CN",
);
$lang = array (
  'title' => '多个翻译创建',
  'addlang' => '创建新的翻译到...',
  'explain' => '你可以以 %lang% 创建以下的新翻译内容',
  'created' => '下面的翻译内容已经被创建',
  'notranslation' => '这个语言已经没有可以翻译的内容了',
)
?>