<?php
 /**
  * This translation file was generated by Anwiki.
  * 
  * Generated on: 08/04/2009 19:42:46
  * By: anw
  * From: it/_i18n/default/actions/action_newtranslations/action_newtranslations
  * Revision: 3452
  */
$anwiki_build = array(
"from" => "it/_i18n/default/actions/action_newtranslations/action_newtranslations",
"rev" => "3452",
"time" => "1239219766",
"lang" => "it",
);
$lang = array (
  'title' => 'Creazione di traduzioni multiple',
  'addlang' => 'Crea nuove traduzioni in...',
  'explain' => 'Puoi creare le seguenti nuove traduzioni in %lang%',
  'created' => 'Sono state create le seguenti traduzioni',
  'notranslation' => 'Non possono essere create ulteriori traduzioni per questa lingua',
)
?>